# -*- coding: utf-8 -*-

import ckan.logic as logic
from ckanext.scheming.helpers import scheming_get_dataset_schema
import json

_get_or_bust = logic.get_or_bust


def get_site_statistics():
    stats = {}
    stats['dataset_count'] = logic.get_action('package_search')(
        {}, {"rows": 1})['count']
    stats['group_count'] = len(logic.get_action('group_list')({}, {}))
    stats['organization_count'] = len(
        logic.get_action('organization_list')({}, {}))
    stats['user_count'] = len(
        logic.get_action('user_list')({}, {}))
    return stats

def data_dict_with_spatial(context, data_dict):
    #t = _get_or_bust(data_dict, "type")
    t = 'dataset'
    expanded = data_dict.get("expanded", True)
    s = scheming_get_dataset_schema(t, expanded)

    longitudes = []
    latitudes = []
    for field in s["dataset_fields"]:
        if field["field_name"] != "location":
            continue
        for choice in scheming_locations_choices(None):
            if choice["value"] not in data_dict.get("location", []):
                continue
            longitudes.append(choice["lon"])
            latitudes.append(choice["lat"])

    if not longitudes or not latitudes:
        return data_dict

    # create buffer (needed to index single-point bboxes)
    # longitude buffer: < 5.6 meters at latitude > 60 degrees
    # latitude buffer: ~11 meters
    e = 0.0001
    lon_min, lon_max = min(longitudes)-e, max(longitudes)+e
    lat_min, lat_max = min(latitudes)-e, max(latitudes)+e
    geometry = {
        "type": "Polygon",
        "coordinates": [
            [
                [lon_min, lat_max],
                [lon_max, lat_max],
                [lon_max, lat_min],
                [lon_min, lat_min],
                [lon_min, lat_max],
            ]
        ],
    }

    value = json.dumps(geometry)
    data_dict.setdefault("extras", [])  # ?
    for item in data_dict["extras"]:
        if item.get("key") == "spatial":
            item["value"] = value
            break
    else:
        data_dict["extras"].append({"key": "spatial", "value": value})

    return data_dict


def scheming_multiple_choice(field):
    if field.get("field_name") == "scientific_name":
        return scheming_scientific_name_choices(field)
    if field.get("field_name") == "location":
        return scheming_locations_choices(field)
    if field.get("field_name") == "tag_string":
        return scheming_tags_choices(field)
    return []


def scheming_tags_choices(field):
    return [
        {"value": "aerial-imagery", "label": "Aerial imagery"},
        {"value": "air-temperature", "label": "Air temperature"},
        {"value": "albedo", "label": "Albedo"},
        {"value": "artificial-nests", "label": "Artificial nests"},
        {"value": "barcoding", "label": "Barcoding"},
        {"value": "birch-forest", "label": "Birch forest"},
        {"value": "camera-traps", "label": "Camera traps"},
        {"value": "dendroecology", "label": "Dendroecology"},
        {"value": "distance-sampling", "label": "Distance sampling"},
        {"value": "dwarf-shrub-heath", "label": "Dwarf shrub heath"},
        {"value": "experimental-exclosures", "label": "Experimental exclosures"},
        {"value": "flight-intercept-traps", "label": "Flight intercept traps"},
        {"value": "forest", "label": "Forest"},
        {"value": "GPS-tags", "label": "GPS tags"},
        {"value": "grassy-tundra", "label": "Grassy tundra"},
        {"value": "ground-ice", "label": "Ground ice"},
        {"value": "ground-temperature", "label": "Ground temperature"},
        {"value": "heath", "label": "Heath"},
        {"value": "humidity", "label": "Humidity"},
        {"value": "hummock-tundra", "label": "Hummock tundra"},
        {"value": "hunting-records", "label": "Hunting records"},
        {"value": "ice-thickness", "label": "Ice thickness"},
        {"value": "icing", "label": "Icing"},
        {"value": "live-trapping", "label": "Live trapping"},
        {"value": "meadow", "label": "Meadow"},
        {"value": "metabarcoding", "label": "Metabarcoding"},
        {"value": "microsatellites", "label": "Microsatellites"},
        {"value": "modelling", "label": "Modelling"},
        {"value": "moss-tundra", "label": "Moss tundra"},
        {"value": "NDVI", "label": "NDVI"},
        {"value": "NIRS", "label": "NIRS"},
        {"value": "pellet-counts", "label": "Pellet counts"},
        {"value": "point-intercept", "label": "Point intercept"},
        {"value": "population-modelling", "label": "Population modelling"},
        {"value": "precipitation", "label": "Precipitation"},
        {"value": "radiation", "label": "Radiation"},
        {"value": "rain-on-snow", "label": "Rain on snow"},
        {"value": "remote-sensing", "label": "Remote sensing"},
        {"value": "repeat-photography", "label": "Repeat photography"},
        {"value": "satellite-imagery", "label": "Satellite imagery"},
        {"value": "satellite-tags", "label": "Satellite tags"},
        {"value": "scat-analysis", "label": "Scat analysis"},
        {"value": "snap-trapping", "label": "Snap trapping"},
        {"value": "snow-beds", "label": "Snow beds"},
        {"value": "snow-depth", "label": "Snow depth"},
        {"value": "snow-melt", "label": "Snow melt"},
        {"value": "snow-modelling", "label": "Snow modelling"},
        {"value": "snow-pits", "label": "Snow pits"},
        {"value": "snow-structure", "label": "Snow structure"},
        {"value": "snow-tracking", "label": "Snow tracking"},
        {"value": "soil-temperature", "label": "Soil temperature"},
        {"value": "stable-isotopes", "label": "Stable isotopes"},
        {"value": "surveys", "label": "Surveys"},
        {"value": "tall-shrub", "label": "Tall shrub"},
        {"value": "temperature", "label": "Temperature"},
        {"value": "temperature-logger", "label": "Temperature logger"},
        {"value": "timing-of-icing", "label": "Timing of icing"},
        {"value": "timing-of-snow-melt", "label": "Timing of snow melt"},
        {"value": "tundra", "label": "Tundra"},
        {"value": "weather-station", "label": "Weather station"},
        {"value": "wind", "label": "Wind"},
    ]


def scheming_locations_choices(field):
    locations = [
        {
            "label": "Svalbard",
            "lon": 16.1761980317877,
            "lat": 78.27838387,
        },
        {
            "label": "Svalbard - Kongsfjorden",
            "lon": 12.00434,
            "lat": 79.061159,
        },
        {
            "label": "Svalbard - Kongsfjorden - Blomstrandoya",
            "lon": 12.10577,
            "lat": 78.975803,
        },
        {
            "label": "Svalbard - Kongsfjorden - Broggerhalvoya",
            "lon": 11.735704,
            "lat": 78.914647,
        },
        {
            "label": "Svalbard - Kongsfjorden - Broggerhalvoya - Simlestupet",
            "lon": 11.735704,
            "lat": 78.914647,
        },
        {
            "label": "Svalbard - Kongsfjorden - Broggerhalvoya - Leinstranda",
            "lon": 11.735704,
            "lat": 78.914647,
        },
        {
            "label": "Svalbard - Kongsfjorden - Kaffioyra",
            "lon": 11.976978,
            "lat": 78.628325,
        },
        {
            "label": "Svalbard - Kongsfjorden - Ossiansarsfjellet",
            "lon": 12.476667,
            "lat": 78.942761,
        },
        {
            "label": "Svalbard - Kongsfjorden - Sarsoyra",
            "lon": 11.647155,
            "lat": 78.756613,
        },
        {
            "label": "Svalbard - Nordenkioldland",
            "lon": 15.116477,
            "lat": 78.013984,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Endalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Janssonhaugen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Bjorndalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Hanaskogdalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Malardalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Todalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Bolterdalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Alkhornet",
            "lon": 13.741739,
            "lat": 78.215766,
        },
        {
            "label": "Svalbard - Nordenskioldland - Colesdalen",
            "lon": 15.202606,
            "lat": 78.080511,
        },
        {
            "label": "Svalbard - Nordenskioldland - Reindalen",
            "lon": 15.765129,
            "lat": 77.950241,
        },
        {
            "label": "Svalbard - Nordenskioldland - Sassendalen",
            "lon": 17.211454,
            "lat": 78.26552,
        },
        {
            "label": "Svalbard - Nordenskioldland - Sassendalen - Gjelhallet",
            "lon": 17.211454,
            "lat": 78.26552,
        },
        {
            "label": "Svalbard - Nordenskioldland - Sassendalen - Eskerdalen",
            "lon": 17.211454,
            "lat": 78.26552,
        },
        {
            "label": "Svalbard - Nordenskioldland - Semmeldalen",
            "lon": 15.416838,
            "lat": 77.966604,
        },
        {
            "label": "Varanger",
            "lon": 29.5298900097758,
            "lat": 70.39534162,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar",
            "lon": 27.514059,
            "lat": 70.60438,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Bekkarfjord",
            "lon": 27.476085,
            "lat": 70.705655,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Eastordalen",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Storelva",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Iesjohka",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Giksjohka",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Gurrojohka",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Suoljavri",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu",
            "lon": 27.85705,
            "lat": 70.907408,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu - Nordkynn",
            "lon": 27.74431,
            "lat": 70.9333935,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu - Tana",
            "lon": 27.7096679608677,
            "lat": 70.07999344,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu - Skjaernes",
            "lon": 27.8498,
            "lat": 70.442,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu - Boftsa",
            "lon": 28.178,
            "lat": 70.3701,
        },
        {
            "label": "Varanger - Bahcaveaijji",
            "lon": 29.185076,
            "lat": 69.78709,
        },
        {
            "label": "Varanger - Bahcaveaijji - Bugoyfjord",
            "lon": 29.3306369580431,
            "lat": 69.89285477,
        },
        {
            "label": "Varanger - Bahcaveaijji - Kirkenes",
            "lon": 29.350363333001,
            "lat": 69.76388,
        },
        {
            "label": "Varanger - Rakkonjarga",
            "lon": 28.8749670228275,
            "lat": 70.65542217,
        },
        {
            "label": "Varanger - Rakkonjarga - Austertana",
            "lon": 28.5673587353134,
            "lat": 70.43537992,
        },
        {
            "label": "Varanger - Rakkonjarga - Luftjok",
            "lon": 28.3815452755338,
            "lat": 70.25333517,
        },
        {
            "label": "Varanger - Rakkonjarga - Polmak",
            "lon": 27.9812148162841,
            "lat": 70.03199545,
        },
        {
            "label": "Varanger - Rakkonjarga - Polmak - Polmak finland",
            "lon": 27.9812148162841,
            "lat": 70.03199545,
        },
        {
            "label": "Varanger - Rakkonjarga - Polmak - Polmak norway",
            "lon": 27.9812148162841,
            "lat": 70.03199545,
        },
        {
            "label": "Varanger - Rakkonjarga - Stjernevann",
            "lon": 29.211285,
            "lat": 70.54163917,
        },
        {
            "label": "Varanger - Varjjatnjarga",
            "lon": 29.7042036634186,
            "lat": 70.36574553,
        },
        {
            "label": "Varanger - Varjjatnjarga - Bergebydalen",
            "lon": 29.016312,
            "lat": 70.236493,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Komagdalen ovre",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Komagdalen midtre",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Komagdalen nedre",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Sanfjorddalen",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Kjoltindan",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Gargas",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Ryggfjellet",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Hubejohka",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Ruossachokka",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Torvhaugdalen",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Baeralveaijohka",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Jakobselv",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Reinhaugen",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Skoarrajohka",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Tranemyra",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Gaasevannan",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
    ]
    for location in locations:
        location['value'] = location['label'].split(' - ')[-1]
    return locations


def scheming_topic_category_choices(field):
    return [
        {"value": "Biota", "label": "Biota"},
        {"value": "Boundaries", "label": "Boundaries"},
        {"value": "Climatology", "label": "Climatology /Meteorology /Atmosphere"},
        {"value": "Economy", "label": "Economy"},
        {"value": "Elevation", "label": "Elevation"},
        {"value": "Environment", "label": "Environment"},
        {"value": "Farming", "label": "Farming"},
        {"value": "Geoscientific", "label": "Geoscientific Information"},
        {"value": "Health", "label": "Health"},
        {"value": "Imagery", "label": "Imagery / Base Maps / Earth Cover"},
        {"value": "Inland_Waters", "label": "Inland Waters"},
        {"value": "Intelligence", "label": "Intelligence / Military"},
        {"value": "Location", "label": "Location"},
        {"value": "Oceans", "label": "Oceans"},
        {"value": "Planning", "label": "Planning / Cadastre"},
        {"value": "Society", "label": "Society"},
        {"value": "Structure", "label": "Structure"},
        {"value": "Transportation", "label": "Transportation"},
        {"value": "utilities", "label": "Utilities / Communication"},
    ]


def scheming_scientific_name_choices(field):
    names = [
{'label': 'Bovidae - Ovis aries (sheep/sau)'},
        {'label': 'Canidae - Canis lupus (gray wolf/ulv)'},
        {'label': 'Canidae - Vulpes lagopus (arctic fox/fjellrev)'},
        {'label': 'Canidae - Vulpes vulpes (red fox/rødrev)'},
        {'label': 'Cervidae - Alces alces (moose/elg)'},
        {'label': 'Cervidae - Capreolus capreolus (roe deer/rådyr)'},
        {'label': 'Cervidae - Rangifer tarandus (reindeer/reinsdyr)'},
        {'label': 'Cricetidae - Lemmus lemmus (norwegian lemming/lemen)'},
        {'label': 'Cricetidae - Microtus agrestis (field vole/markmus)'},
        {'label': 'Cricetidae - Microtus levis (sibling vole/østmarkmus)'},
        {'label': 'Cricetidae - Microtus oeconomus (tundra vole/fjellmarkmus alt fjellrotte)'},
        {'label': 'Cricetidae - Myodes glareolus (bank vole/klatremus)'},
        {'label': 'Cricetidae - Myodes rufocanus (grey-sided vole/gråsidemus)'},
        {'label': 'Cricetidae - Myodes rutilus (northern red-backed vole/rødmus)'},
        {'label': 'Felidae - Lynx lynx (eurasian lynx/gaupe)'},
        {'label': 'Leporidae - Lepus timidus (mountain hare/hare)'},
        {'label': 'Mustelidae - Gulo gulo (wolverine/jerv)'},
        {'label': 'Mustelidae - Lutra lutra (eurasian otter/oter)'},
        {'label': 'Mustelidae - Mustela erminea (stoat/røyskatt)'},
        {'label': 'Mustelidae - Mustela nivalis (least weasel/snømus)'},
        {'label': 'Mustelidae - Neovison vison (american mink/mink)'},
        {'label': 'Soricidae - Neomys fodiens (water shrew/vannspissmus)'},
        {'label': 'Soricidae - Sorex araneus (common shrew/vanlig spissmus alt krattspissmus)'},
        {'label': 'Soricidae - Sorex caecutiens (masked shrew/lappspsimus)'},
        {'label': 'Soricidae - Sorex minutissimus (least shrew/knøttspismus)'},
        {'label': 'Soricidae - Sorex minutus (pygmy shrew/dvergspissmus)'},
        {'label': 'Soricidae - Sorex sp'},
        {'label': 'Ursidae - Ursus arctos (brown bear/brunbjørn)'},
        {'label': 'Ursidae - Ursus maritima (polar bear/isbjørn)'},
        {'label': 'Acanthis hornemanni (arctic redpoll/polarsisik)'},
        {'label': 'Actitis hypoleucos (common sandpiper/strandsnipe)'},
        {'label': 'Anas crecca (teal/krikkand)'},
        {'label': 'Anser brachyrhynchus (pink-footed goose/kortnebbgås)'},
        {'label': 'Anthus cervinus (red-throated pipit/lappiplerke)'},
        {'label': 'Anthus pratensis (meadow pipit/heipiplerke)'},
        {'label': 'Anthus sp (pipit/piplerke)'},
        {'label': 'Anthus trivialis (tree pipit/trepiplerke)'},
        {'label': 'Aquila chrysaetos (golden eagle/kongeørn)'},
        {'label': 'Arenaria interpes (turnstone/steinvender)'},
        {'label': 'Asio flammeus (short-eared owl/jordugle)'},
        {'label': 'Aythya marila (scaup/bergand)'},
        {'label': 'Bombycilla garrulus (bohemian waxwing/sidensvans)'},
        {'label': 'Branta bernicla (brent goose/ringgås)'},
        {'label': 'Branta leucopsis (barnacle goose/hvitkinngås)'},
        {'label': 'Bubo scandiacus (snowy owl/snøugle)'},
        {'label': 'Bucephala clangula (common goldeneye/kvinand)'},
        {'label': 'Buteo lagopus (rough-legged buzzard/fjellvåk)'},
        {'label': 'Calcarius lapponicus (lapland bunting/lappspurv)'},
        {'label': 'Calidris alba (sanderling/sandløper)'},
        {'label': 'Calidris alpina (dunlin/myrsnipe)'},
        {'label': 'Calidris maritima (purple sandpiper/fjæreplytt)'},
        {'label': 'Calidris minuta (little stint/dvergsnipe)'},
        {'label': "Calidris temminckii (temminck's stint/temmincksnipe)"},
        {'label': 'Carduelis chloris (european greenfinch/grønnfink)'},
        {'label': 'Carduelis flammea (common redpoll/gråsisik)'},
        {'label': 'Charadirus morinellus (dotterel/boltit)'},
        {'label': 'Charadrius hiaticula (ringed plover/sandlo)'},
        {'label': 'Cinclus cinclus (dipper/fossekall)'},
        {'label': 'Clangula hyemalis (long-tailed duck/havelle)'},
        {'label': 'Corvus corax (common raven/ravn)'},
        {'label': 'Corvus cornix (hooded crow/kråke)'},
        {'label': 'Cuculus canorus (common cuckoo/gjøk)'},
        {'label': 'Emberiza schoeniclus (common reed bunting/sivspurv)'},
        {'label': 'Eremophila alpestris (horned lark/fjellerke)'},
        {'label': 'Falco columbarius (merlin/dvergfalk)'},
        {'label': 'Falco peregrinus (peregrin falcon/vandrefalk)'},
        {'label': 'Falco rusticolus (gyrfalcon/jaktfalk)'},
        {'label': 'Falco tinnunculus (common kestrel/tårnfalk)'},
        {'label': 'Ficedula hypoleuca (pied flycatcher/svarthvit fluesnapper)'},
        {'label': 'Fringilla montifringilla (brambling/bjørkefink)'},
        {'label': 'Gallinago gallinago (common snipe/enkeltbekkasin)'},
        {'label': 'Gavia arctica (black-throated diver/storlom)'},
        {'label': 'Gavia stellata (red-throated diver/smålom)'},
        {'label': 'Haliaeetus albicilla (white-tailed eagle/havørn)'},
        {'label': 'Lagopus lagopus (willow ptarmigan/lirype)'},
        {'label': 'Lagopus muta (rock ptarmigan/fjellrype)'},
        {'label': 'Lagopus muta hyperborea (svalbard rock ptarmigan/svalbardrype)'},
        {'label': 'Lagopus sp (ptarmigan/rype)'},
        {'label': 'Lanius excubitor (great grey shrike/varsler)'},
        {'label': 'Larus canus (common gull/fiskemåke)'},
        {'label': 'Limosa lapponica (bar-tailed godwit/lappspove)'},
        {'label': 'Loxia curvirostra (red crossbill/grankorsnebb)'},
        {'label': 'Luscinia svecica (bluethroat/blåstrupe)'},
        {'label': 'Mergus merganser (common merganser/laksand)'},
        {'label': 'Mergus serrator (red-breasted merganser/siland)'},
        {'label': 'Motacilla alba (white wagtail/linerle)'},
        {'label': 'Motacilla flava thunbergi (grey-headed wagtail/såerle)'},
        {'label': 'Numenius phaeopus (whimbrel/småspove)'},
        {'label': 'Oenanthe oenanthe (northern wheatear/steinskvett)'},
        {'label': 'Pagophila eburnea (ivory gull/ismåke)'},
        {'label': 'Parus major (great tit/kjøttmeis)'},
        {'label': 'Perisoreus infaustus (siberian jay/lavskrike)'},
        {'label': 'Phalaropus fulicarius (red phalarope/polarsvømmesnipe)'},
        {'label': 'Phalaropus lobatus (red-necked phalarope/svømmesnipe)'},
        {'label': 'Philomachus pugnax (ruff/brushøne)'},
        {'label': 'Phoenicurus phoenicurus (common redstart/rødstjert)'},
        {'label': 'Phylloscopus borealis (arctic warbler/lappsanger)'},
        {'label': 'Phylloscopus trochilus (willow warbler/løvsanger)'},
        {'label': 'Pica pica (common magpie/skjære)'},
        {'label': 'Plectrophenax nivalis (snow bunting/snøspurv)'},
        {'label': 'Pluvialis apricaria (eurasian golden plover/heilo)'},
        {'label': 'Poecile cinctus (siberian tit/lappmeis)'},
        {'label': 'Poecile montanus (willow tit/granmeis)'},
        {'label': 'Scolopax rusticola (eurasian woodcock/rugde)'},
        {'label': 'Stercorarius longicaudus (long-tailed skua/fjelljo)'},
        {'label': 'Stercorarius parasiticus (arctic skua/tyvjo)'},
        {'label': 'Sterna paradisaea (arctic tern/rødnebbterne)'},
        {'label': 'Surnia ulula (northern hawk-owl/haukugle)'},
        {'label': 'Tringa glareola (wood sandpiper/grønnstilk)'},
        {'label': 'Tringa totanus (redshank/rødstilk)'},
        {'label': 'Turdus iliacus (redwing/rødvingetrost)'},
        {'label': 'Turdus philomelos (song thrush/måltrost)'},
        {'label': 'Turdus pilaris (fieldfare/gråtrost)'},
        {'label': 'Apiaceae - Angelica archangelica (garden angelica/kvann)'},
        {'label': 'Apiaceae - Anthriscus sylvestris (cow parsley/hundekjeks)'},
        {'label': 'Asteraceae  - Cirsium heterophyllum (melancholy thistle/kvitbladtistel)'},
        {'label': 'Asteraceae  - Solidago virgaurea (goldenrod/gullris)'},
        {'label': 'Asteraceae - Hieracium (hawkweed/svæve)'},
        {'label': 'Asteraceae - Hieracium alpina agg (fjellsvæver)'},
        {'label': 'Asteraceae - Omalotheca norvegica (highland cudweed/setergråurt)'},
        {'label': 'Asteraceae - Omalotheca supina (dwarf cudweed/dverggråurt)'},
        {'label': 'Asteraceae - Saussurea alpina (alpine saw-wort/fjelltistel)'},
        {'label': 'Asteraceae - Scorzoneroides autumnalis  (autumn hawkbit/følblom)'},
        {'label': 'Asteraceae - Taraxacum (dandelion/løvetann)'},
        {'label': 'Athyriaceae - Athyrium (lady-fern/storburkne)'},
        {'label': 'Athyriaceae - Athyrium (storburkne)'},
        {'label': 'Athyriaceae - Athyrium distentifolium (alpine lady-fern/fjellburkne)'},
        {'label': 'Betulaceae - Alnus (alder/or)'},
        {'label': 'Betulaceae - Alnus incana (grey alder/gråor)'},
        {'label': 'Betulaceae - Betula nana (dwarf birch/dvergbjørk)'},
        {'label': 'Betulaceae - Betula pubescens var pumila (downy birch/fjellbjørk)'},
        {'label': 'Boraginaceae - Myosotis (forget-me-not/minneblom)'},
        {'label': 'Brassicaceae - Cardamine pratensis agg (cuckooflower/engkarse)'},
        {'label': 'Campanulaceae - Campanula rotundifolia coll (harebell/blåklokke)'},
        {'label': 'Caryophyllaceae - Cerastium (mouse-ear/arve)'},
        {'label': 'Caryophyllaceae - Cerastium alpinum agg (alpine mouse-ear/fjellarve)'},
        {'label': 'Caryophyllaceae - Cerastium cerastoides (starwort mouse-ear/brearve)'},
        {'label': 'Caryophyllaceae - Cerastium fontanum (common mouse-ear/arve)'},
        {'label': 'Caryophyllaceae - Minuartia (sandwort/tuvearve)'},
        {'label': 'Caryophyllaceae - Sagina (pearlwort/småarve)'},
        {'label': 'Caryophyllaceae - Sagina saginoides (alpine pearlwort/seterarve)'},
        {'label': 'Caryophyllaceae - Stellaria (stitchwort/stjerneblom)'},
        {'label': 'Caryophyllaceae - Stellaria borealis (fjellstjerneblom)'},
        {'label': 'Caryophyllaceae - Stellaria media (common chickweed/vassarve)'},
        {'label': 'Caryophyllaceae - Stellaria nemorum (wood stitchwort/skogstjerneblom)'},
        {'label': 'Celastraceae - Parnassia palustris (grass-of-parnassus/jåblom)'},
        {'label': 'Cornaceae - Chamaepericlymenum suecicum  (dwarf cornel/skrubbær)'},
        {'label': 'Crassulaceae - Rhodiola rosea (roseroot/rosenrot)'},
        {'label': 'Cupressaceae - Juniperus communis (common juniper/einer)'},
        {'label': 'Cyperaceae - Carex aquatilis agg (water sedge/nordlandsstarr)'},
        {'label': 'Cyperaceae - Carex bigelowii (stiff sedge/stivstarr)'},
        {'label': 'Cyperaceae - Carex brunnescens (seterstarr)'},
        {'label': 'Cyperaceae - Carex canescens (gråstarr)'},
        {'label': "Cyperaceae - Carex lachenalii (hare's-foot sedge/rypestarr)"},
        {'label': 'Cyperaceae - Carex limosa (bog-sedge/dystarr)'},
        {'label': 'Cyperaceae - Carex livida (blystarr)'},
        {'label': 'Cyperaceae - Carex nigra (common sedge/slåttestarr)'},
        {'label': 'Cyperaceae - Carex saxatilis  (blankstarr)'},
        {'label': 'Cyperaceae - Carex sp  (sedge/starr)'},
        {'label': 'Cyperaceae - Carex vaginata (sheathed sedge/slirestarr)'},
        {'label': 'Cyperaceae - Eriophorum angustifolium (common cottongrass/duskull)'},
        {'label': 'Cyperaceae - Trichophorum cespitosum (deergrass/bjønnskjegg)'},
        {'label': 'Equisetaceae  - Equisetum (horsetail/sneller)'},
        {'label': 'Equisetaceae - Equisetum arvense (field horsetail/åkersnelle)'},
        {'label': 'Equisetaceae - Equisetum palustre (marsh horsetail/myrsnelle)'},
        {'label': 'Equisetaceae - Equisetum pratense (shady horsetail/engsnelle)'},
        {'label': 'Equisetaceae - Equisetum sylvaticum (wood horsetail/skogsnelle)'},
        {'label': 'Equisetaceae - Equisetum variegatum (variegated horsetail/fjellsnelle)'},
        {'label': 'Ericaceae - Andromeda polifolia (bog-rosemary/kvitlyng)'},
        {'label': 'Ericaceae - Arctous alpinus (arctic bearberry/rypebær)'},
        {'label': 'Ericaceae - Empetrum nigrum  (crowberry/krekling)'},
        {'label': 'Ericaceae - Harrimanella hypnoides (moselyng)'},
        {'label': 'Ericaceae - Kalmia procumbens (trailing azalea/greplyng)'},
        {'label': 'Ericaceae - Orthilia secunda (serrated wintergreen/nikkevintergrøn)'},
        {'label': 'Ericaceae - Phyllodoce caerulea (blue heath/blålyng)'},
        {'label': 'Ericaceae - Pyrola (wintergreen/vintergrøn)'},
        {'label': 'Ericaceae - Pyrola minor (common wintergreen/perlevintergrøn)'},
        {'label': 'Ericaceae - Rhododendron tomentosum (labrador tea/finnmarkspors)'},
        {'label': 'Ericaceae - Vaccinium myrtillus (bilberry/blåbær)'},
        {'label': 'Ericaceae - Vaccinium uliginosum (bog bilberry/blokkebær)'},
        {'label': 'Ericaceae - Vaccinium vitis-idaea (cowberry/tyttebær)'},
        {'label': 'Geraniaceae - Geranium sylvaticum (wood crane`s-bill/skogstorkenebb)'},
        {'label': 'Juncaceae - Juncus (rush/siv)'},
        {'label': 'Juncaceae - Juncus filiformis (thread rush/trådsiv)'},
        {'label': 'Juncaceae - Juncus trifidus (three-leaved rush/rabbesiv)'},
        {'label': 'Juncaceae - Luzula (wood-rush/frytle)'},
        {'label': 'Juncaceae - Luzula multiflora (heath wood-rush/engfrytle)'},
        {'label': 'Juncaceae - Luzula pilosa (hairy wood-rush/hårfrytle)'},
        {'label': 'Juncaceae - Luzula sudetica (myrfrytle)'},
        {'label': 'Lentibulariaceae - Pinguicula vulgaris (common butterwort/vanleg tettegras)'},
        {'label': 'Linnaeaceae  - Linnaea borealis (twinflower/linnea)'},
        {'label': 'Lycopodiaceae  - Huperzia selago (fir clubmoss/lusegras)'},
        {'label': 'Lycopodiaceae  - Lycopodium (clubmoss/kråkefot)'},
        {'label': 'Lycopodiaceae - Diphasiastrum alpinum (alpine clubmoss/fjelljamne)'},
        {'label': 'Lycopodiaceae - Huperzia selago (polarlusegras)'},
        {'label': 'Lycopodiaceae - Lycopodium annotinum (interrupted clubmoss/stri kråkefot)'},
        {'label': 'Lycopodiaceae - Lycopodium clavatum (stag`s-horn clubmoss/mjuk kråkefot)'},
        {'label': 'Myrsinaceae  - Trientalis europaea (chickweed-wintergreen/skogstjerne)'},
        {'label': 'Onagraceae - Chamerion angustifolium (rosebay willowherb/geitrams)'},
        {'label': 'Onagraceae - Epilobium (willowherb/mjølke)'},
        {'label': 'Onagraceae - Epilobium anagallidifolium (alpine willowherb/dvergmjølke)'},
        {'label': 'Onagraceae - Epilobium hornemannii (setermjølke)'},
        {'label': 'Onagraceae - Epilobium palustre (marsh willowherb/myrmjølke)'},
        {'label': 'Ophioglossaceae - Botrychium lunaria (moonwort/marinøkkel)'},
        {'label': 'Orobanchaceae - Bartsia alpina (alpine bartsia/svarttopp)'},
        {'label': 'Orobanchaceae - Euphrasia (eyebright/augnetrøst)'},
        {'label': 'Orobanchaceae - Euphrasia wettsteinii (fjellaugnetrøst)'},
        {'label': 'Orobanchaceae - Melampyrum (cow-wheat/marimjelle)'},
        {'label': 'Orobanchaceae - Melampyrum pratense (common cow-wheat/stormarimjelle)'},
        {'label': 'Orobanchaceae - Melampyrum sylvaticum (small cow-wheat/småmarimjelle)'},
        {'label': 'Orobanchaceae - Pedicularis (lousewort/myrklegg)'},
        {'label': 'Orobanchaceae - Pedicularis lapponica (bleikmyrklegg)'},
        {'label': 'Orobanchaceae - Rhinanthus minor (yellow-rattle/småengkall)'},
        {'label': 'Plantaginaceae - Veronica (speedwell/veronika)'},
        {'label': 'Plantaginaceae - Veronica alpina (alpine speedwell/fjellveronika)'},
        {'label': 'Poaceae - Agrostis (bent/kvein)'},
        {'label': 'Poaceae - Agrostis mertensii (fjellkvein)'},
        {'label': 'Poaceae - Anthoxanthum nipponicum (fjellgulaks)'},
        {'label': 'Poaceae - Anthoxanthum odoratum (sweet vernal-grass/gulaks)'},
        {'label': 'Poaceae - Avenella flexuosa (wavy hair-grass/smyle)'},
        {'label': 'Poaceae - Calamagrostis (small-reed/rørkvein)'},
        {'label': 'Poaceae - Calamagrostis lapponica (finnmarksrørkvein)'},
        {'label': 'Poaceae - Calamagrostis neglecta (smårørkvein)'},
        {'label': 'Poaceae - Calamagrostis phragmitoides  (scandinavian small-reed/skogrørkvein)'},
        {'label': 'Poaceae - Deschampsia alpina (fjellbunke)'},
        {'label': 'Poaceae - Deschampsia cespitosa (tufted hair-grass/sølvbunke)'},
        {'label': 'Poaceae - Festuca (fescues/svingel)'},
        {'label': 'Poaceae - Festuca ovina (sheep`s-fescue/sauesvingel)'},
        {'label': 'Poaceae - Festuca rubra (red fescues/raudsvingel)'},
        {'label': 'Poaceae - Festuca rubra ssp richardsonii (polarraudsvingel)'},
        {'label': 'Poaceae - Hierochloe odorata (holy-grass/vanleg marigras)'},
        {'label': 'Poaceae - Milium effusum (wood millet/myskegras)'},
        {'label': 'Poaceae - Nardus stricta (mat-grass/finnskjegg)'},
        {'label': "Poaceae - Phleum alpinum (alpine cat's-tail/fjelltimotei)"},
        {'label': 'Poaceae - Poa (meadow-grass/rapp)'},
        {'label': 'Poaceae - Poa alpina (alpine meadow-grass/fjellrapp)'},
        {'label': 'Poaceae - Poa arctica (jervrapp)'},
        {'label': 'Poaceae - Poa pratensis ssp alpigena (seterrapp)'},
        {'label': 'Poaceae - Trisetum spicatum (svartaks)'},
        {'label': 'Poaceae - Vahlodea atropurpurea (rypebunke)'},
        {'label': 'Polygonaceae - Bistorta vivipara (alpine bistort/harerug)'},
        {'label': 'Polygonaceae - Oxyria digyna (mountain sorrel/fjellsyre)'},
        {'label': 'Polygonaceae - Rumex acetosa (common sorrel/engsyre)'},
        {'label': 'Ranunculaceae - Caltha palustris (marsh-marigold/bekkeblom)'},
        {'label': 'Ranunculaceae - Ranunculus (buttercup/soleie)'},
        {'label': 'Ranunculaceae - Ranunculus acris agg (meadow buttercup/engsoleie)'},
        {'label': 'Ranunculaceae - Ranunculus repens (creeping buttercup/krypsoleie)'},
        {'label': 'Ranunculaceae - Thalictrum alpinum (alpine meadow-rue/fjellfrøstjerne)'},
        {'label': 'Ranunculaceae - Trollius europaeus (globeflower/ballblom)'},
        {'label': "Rosaceae - Alchemilla (lady's-mantle/marikåpe)"},
        {'label': "Rosaceae - Alchemilla alpina (alpine lady's-mantle/fjellmarikåpe)"},
        {'label': 'Rosaceae - Comarum palustre (marsh cinquefoil/myrhatt)'},
        {'label': 'Rosaceae - Filipendula ulmaria (meadowsweet/mjødurt)'},
        {'label': 'Rosaceae - Geum rivale (water avens/enghumleblom)'},
        {'label': 'Rosaceae - Potentilla norvegica (ternate-leaved cinquefoil/norsk mure)'},
        {'label': 'Rosaceae - Rubus chamaemorus (cloudberry/molte)'},
        {'label': 'Rosaceae - Rubus saxatalis (stone bramble/teiebær)'},
        {'label': 'Rosaceae - Sibbaldia procumbens (sibbaldia/trefingerurt)'},
        {'label': 'Rosaceae - Sorbus aucuparia (rowan/rogn)'},
        {'label': 'Salicaceae  - Salix (willow/vier)'},
        {'label': 'Salicaceae  - Salix herbacea (dwarf willow/musøre)'},
        {'label': 'Salicaceae - Salix glauca (sølvvier)'},
        {'label': 'Salicaceae - Salix hastata (bleikvier)'},
        {'label': 'Salicaceae - Salix lanata agg (woolly willow/ullvier)'},
        {'label': 'Salicaceae - Salix lapponum (downy willow/lappvier)'},
        {'label': 'Salicaceae - Salix phylicifolia agg (tea-leaved willow/grønvier)'},
        {'label': 'Selaginellaceae - Selaginella selaginoides (lesser clubmoss/dvergjamne)'},
        {'label': 'Violaceae - Viola (violet/fiol)'},
        {'label': 'Violaceae - Viola biflora (fjellfiol)'},
        {'label': 'Violaceae - Viola epipsila (stor myrfiol)'},
        {'label': 'Violaceae - Viola palustris agg (marsh violet/myrfiol)'},
        {'label': 'Amblystegiaceae  - Sanionia uncinata (bleikmose)'},
        {'label': 'Anastrophyllaceae - Barbilophozia sp (skjeggmose)'},
        {'label': 'Brachytheciaceae - Brachythecium sp (lundmose)'},
        {'label': 'Brachytheciaceae - Sciuro-hypnum sp (sprikelundmose)'},
        {'label': 'Bryaceae - Bryum sp (vrangmose)'},
        {'label': 'Dicranaceae - Dicranum flexicaule (lyngsigd)'},
        {'label': 'Dicranaceae - Dicranum scoparium (ribbesigd)'},
        {'label': 'Dicranaceae - Dicranum sp (sigdmose)'},
        {'label': 'Ditrichaceae - Distichium sp (planmose)'},
        {'label': 'Grimmiaceae - Racomitrium sp (gråmose)'},
        {'label': 'Hylocomiaceae - Hylocomiastrum pyrenaicum (seterhusmose)'},
        {'label': 'Hylocomiaceae - Hylocomiastrum sp (husmose)'},
        {'label': 'Hylocomiaceae - Hylocomium sp (etasjemose)'},
        {'label': 'Hylocomiaceae - Hylocomium splendens (etasjemose)'},
        {'label': 'Hylocomiaceae - Pleurozium schreberi (furumose)'},
        {'label': 'Hylocomiaceae - Pleurozium sp (furumose)'},
        {'label': 'Lophoziaceae - Lophozia sp (flikmose)'},
        {'label': 'Lophoziaceae - Lophozia wenzelii (skeiflik)'},
        {'label': 'Mielichhoferiaceae - Pohlia sp (nikkemose)'},
        {'label': 'Mielichhoferiaceae - Pohlia wahlenbergii (kaldnikke)'},
        {'label': 'Polytrichaceae - Oligotrichum hercynicum (grusmose)'},
        {'label': 'Polytrichaceae - Oligotrichum sp (grusmose)'},
        {'label': 'Polytrichaceae - Polytrichum sp (bjørnemose)'},
        {'label': 'Polytrichaceae - Psilopilum sp (komagmose)'},
        {'label': 'Rhabdoweisiaceae - Arctoa fulvella (faksjøkelmose)'},
        {'label': 'Rhabdoweisiaceae - Arctoa sp (jøkelmose)'},
        {'label': 'Rhabdoweisiaceae - Kiaeria glacialis (jøkelfrostmose)'},
        {'label': 'Rhabdoweisiaceae - Kiaeria sp (frostmose)'},
        {'label': 'Sphagnaceae - Sphagnum russowii (tvaretorvmose)'},
        {'label': 'Sphagnaceae - Sphagnum sp (peat moss/torvmose)'},
        {'label': 'Agyrtidae - Pteroloma forsstromii'},
        {'label': 'Anthribidae - Gonotropis dorsalis'},
        {'label': 'Byrrhidae - Byrrhus fasciatus'},
        {'label': 'Byrrhidae - Cytilus sericeus'},
        {'label': 'Byrrhidae - Simplocaria semistriata'},
        {'label': 'Cantharidae - Dichelotarsus lapponicus'},
        {'label': 'Cantharidae - Malthodes brevicollis'},
        {'label': 'Cantharidae - Malthodes fuscus'},
        {'label': 'Cantharidae - Malthodes guttifer'},
        {'label': 'Cantharidae - Malthodes mysticus'},
        {'label': 'Cantharidae - Podabrus alpinus'},
        {'label': 'Cantharidae - Podistra schoenherri'},
        {'label': 'Cantharidae - Rhagonycha elongata'},
        {'label': 'Cantharidae - Rhagonycha nigriventris'},
        {'label': 'Carabidae - Agonum consimile'},
        {'label': 'Carabidae - Amara apricaria'},
        {'label': 'Carabidae - Amara hyperborea'},
        {'label': 'Carabidae - Amara nigricornis'},
        {'label': 'Carabidae - Bembidion grapii'},
        {'label': 'Carabidae - Dromius agilis'},
        {'label': 'Carabidae - Loricera pilicornis'},
        {'label': 'Carabidae - Miscodera arctica'},
        {'label': 'Carabidae - Notiophilus aquaticus'},
        {'label': 'Cerambycidae - Judolia sexmaculata'},
        {'label': 'Cerambycidae - Rhagium mordax (løvtreløper)'},
        {'label': 'Cerylonidae - Cerylon ferrugineum'},
        {'label': 'Chrysomelidae - Clytra quadripunctata'},
        {'label': 'Chrysomelidae - Gonioctena intermedia'},
        {'label': 'Chrysomelidae - Lochmaea caprea'},
        {'label': 'Chrysomelidae - Phratora vitellinae'},
        {'label': 'Ciidae - Cis bidentatus'},
        {'label': 'Ciidae - Cis boleti'},
        {'label': 'Ciidae - Cis comptus'},
        {'label': 'Ciidae - Cis submicans'},
        {'label': 'Ciidae - Orthocis alni'},
        {'label': 'Ciidaqe - Cis comptus'},
        {'label': 'Cleridae - Necrobia violacea'},
        {'label': 'Coccinellidae - Calvia quatuordecimguttata'},
        {'label': 'Coccinellidae - Coccinella hieroglyphica'},
        {'label': 'Coccinellidae - Coccinella trifasciata (fjellmarihøne)'},
        {'label': 'Coccinellidae - Nephus bipunctatus'},
        {'label': 'Coccinellidae - Scymnus frontalis'},
        {'label': 'Coccinellidae - Scymnus nigrinus'},
        {'label': 'Cryptophagidae - Atomaria affinis'},
        {'label': 'Cryptophagidae - Atomaria apicalis'},
        {'label': 'Cryptophagidae - Atomaria hislopi'},
        {'label': 'Cryptophagidae - Atomaria lewisi'},
        {'label': 'Cryptophagidae - Atomaria nitidula'},
        {'label': 'Cryptophagidae - Atomaria peltataeformis'},
        {'label': 'Cryptophagidae - Cryptophagus corticinus'},
        {'label': 'Cryptophagidae - Cryptophagus lapponicus'},
        {'label': 'Cryptophagidae - Cryptophagus tuberculosus'},
        {'label': 'Curculionidae - Coeliodinus rubicundus'},
        {'label': 'Curculionidae - Hylastes brunneus (fururotbille)'},
        {'label': 'Curculionidae - Magdalis carbonaria'},
        {'label': 'Curculionidae - Otiorhynchus nodosus'},
        {'label': 'Curculionidae - Pityogenes bidentatus (totannet barkbille)'},
        {'label': 'Curculionidae - Pityogenes chalcographus'},
        {'label': 'Curculionidae - Polydrusus fulvicornis'},
        {'label': 'Curculionidae - Rhinoncus castor'},
        {'label': 'Curculionidae - Trypodendron signatum'},
        {'label': 'Dytiscidae - Agabus congener'},
        {'label': 'Elateridae - Ampedus nigrinus (svart blodsmeller)'},
        {'label': 'Elateridae - Athous subfuscus'},
        {'label': 'Elateridae - Denticollis borealis'},
        {'label': 'Elateridae - Denticollis linearis (øyesmeller)'},
        {'label': 'Elateridae - Diacanthous undulatus (huldresmeller)'},
        {'label': 'Elateridae - Eanus costalis (tundrasmeller)'},
        {'label': 'Elateridae - Liotrichus affinis (bjørkesmeller)'},
        {'label': 'Elateridae - Neohypdonus arcticus (grussmeller)'},
        {'label': 'Elateridae - Orithales serraticornis'},
        {'label': 'Elateridae - Paraphotistus impressus (hårsmeller)'},
        {'label': 'Elateridae - Pheletes aeneoniger (skogsmeller)'},
        {'label': 'Elateridae - Selatosomus melancholicus'},
        {'label': 'Elateridae - Sericus brunneus (brunsmeller)'},
        {'label': 'Elmidae - Oulimnius tuberculatus'},
        {'label': 'Erotylidae - Triplax aenea'},
        {'label': 'Erotylidae - Triplax russica'},
        {'label': 'Erotylidae - Triplax scutellaris'},
        {'label': 'Geometridae - Agriopis aurantiaria (scarce umber moth/gul frostmåler)'},
        {'label': 'Geometridae - Epirrita autumnata (autumnal moth/fjellbjørkemåler)'},
        {'label': 'Geometridae - Operophtera brumata (winter moth/liten frostmåler)'},
        {'label': 'Hydrophilidae - Cercyon lateralis'},
        {'label': 'Hydrophilidae - Cercyon melanocephalus'},
        {'label': 'Hydrophilidae - Cercyon quisquilius'},
        {'label': 'Hydrophilidae - Cryptopleurum minutum'},
        {'label': 'Hydrophilidae - Megasternum concinnum'},
        {'label': 'Latridiidae - Corticaria ferruginea'},
        {'label': 'Latridiidae - Corticaria orbicollis'},
        {'label': 'Latridiidae - Corticaria rubripes'},
        {'label': 'Latridiidae - Corticarina minuta'},
        {'label': 'Latridiidae - Cortinicara gibbosa'},
        {'label': 'Latridiidae - Dienerella filum'},
        {'label': 'Latridiidae - Enicmus fungicola'},
        {'label': 'Latridiidae - Enicmus lundbladi'},
        {'label': 'Latridiidae - Latridius consimilis'},
        {'label': 'Latridiidae - Latridius hirtus'},
        {'label': 'Latridiidae - Latridius minutus'},
        {'label': 'Latridiidae - Latridius porcatus'},
        {'label': 'Leiodidae - Agathidium arcticum'},
        {'label': 'Leiodidae - Agathidium confusum'},
        {'label': 'Leiodidae - Agathidium rotundatum'},
        {'label': 'Leiodidae - Anisotoma axillaris'},
        {'label': 'Leiodidae - Anisotoma castanea'},
        {'label': 'Leiodidae - Anisotoma glabra'},
        {'label': 'Leiodidae - Catops alpinus'},
        {'label': 'Leiodidae - Catops nigrita'},
        {'label': 'Leiodidae - Catops tristis'},
        {'label': 'Leiodidae - Colon serripes'},
        {'label': 'Leiodidae - Hydnobius septentrionalis'},
        {'label': 'Leiodidae - Leiodes gyllenhalii'},
        {'label': 'Leiodidae - Leiodes inordinata'},
        {'label': 'Leiodidae - Leiodes obesa'},
        {'label': 'Leiodidae - Leiodes punctulata'},
        {'label': 'Leiodidae - Leiodes silesiaca'},
        {'label': 'Lymexylidae - Elateroides dermestoides'},
        {'label': 'Melandryidae - Abdera affinis'},
        {'label': 'Melandryidae - Orchesia micans'},
        {'label': 'Melandryidae - Orchesia minor'},
        {'label': 'Melyridae - Aplocnemus tarsalis'},
        {'label': 'Melyridae - Dasytes obscurus'},
        {'label': 'Melyridae - Necrobia violacea'},
        {'label': 'Monotomidae - Rhizophagus dispar'},
        {'label': 'Mycetophagidae - Mycetophagus multipunctatus'},
        {'label': 'Nitidulidae - Epuraea aestiva'},
        {'label': 'Nitidulidae - Epuraea angustula'},
        {'label': 'Nitidulidae - Epuraea binotata'},
        {'label': 'Nitidulidae - Epuraea boreella'},
        {'label': 'Nitidulidae - Epuraea melina'},
        {'label': 'Nitidulidae - Epuraea rufomarginata'},
        {'label': 'Nitidulidae - Epuraea silacea'},
        {'label': 'Nitidulidae - Glischrochilus quadripunctatus'},
        {'label': 'Phalacridae - Phalacrus substriatus'},
        {'label': 'Ptiliidae - Acrotrichis cognata'},
        {'label': 'Ptiliidae - Acrotrichis fascicularis'},
        {'label': 'Ptiliidae - Acrotrichis intermedia'},
        {'label': 'Ptiliidae - Acrotrichis parva'},
        {'label': 'Ptiliidae - Acrotrichis rugulosa'},
        {'label': 'Ptiliidae - Acrotrichis sericans'},
        {'label': 'Ptiliidae - Acrotrichis silvatica'},
        {'label': 'Ptiliidae - Acrotrichis strandi'},
        {'label': 'Rhynchitidae - Deporaus betulae'},
        {'label': 'Salpingidae - Rabocerus foveolatus'},
        {'label': 'Salpingidae - Salpingus ruficollis'},
        {'label': 'Scarabaeidae - Aphodius borealis'},
        {'label': 'Scarabaeidae - Aphodius depressus'},
        {'label': 'Scarabaeidae - Aphodius fasciatus (smågjødselbille)'},
        {'label': 'Scarabaeidae - Aphodius lapponum (fjellgjødselbille)'},
        {'label': 'Scarabaeidae - Aphodius piceus (svartgjødselbille)'},
        {'label': 'Scarabaeidae - Protaetia metallica (maurgullbasse)'},
        {'label': 'Scirtidae - Cyphon padi'},
        {'label': 'Scirtidae - Cyphon variabilis'},
        {'label': 'Scraptiidae - Anaspis arctica'},
#        {'label': 'Scydmaenidae - Stenichnus bicolor'},
        {'label': 'Silphidae - Nicrophorus vespilloides'},
        {'label': 'Silphidae - Thanatophilus lapponicus'},
        {'label': 'Silvanidae - Pediacus fuscus'},
        {'label': 'Sphaeritidae - Sphaerites glabratus'},
        {'label': 'Sphindidae - Aspidiphorus orbiculatus'},
        {'label': 'Staphylinidae - Acidota crenata'},
        {'label': 'Staphylinidae - Acrostiba borealis'},
        {'label': 'Staphylinidae - Acrotona amblystegii'},
        {'label': 'Staphylinidae - Acrotona fungi'},
        {'label': 'Staphylinidae - Acrotona orbata'},
        {'label': 'Staphylinidae - Acrulia inflata'},
        {'label': 'Staphylinidae - Aleochara brundini'},
        {'label': 'Staphylinidae - Aleochara moerens'},
        {'label': 'Staphylinidae - Amischa analis'},
        {'label': 'Staphylinidae - Anthophagus alpinus'},
        {'label': 'Staphylinidae - Anthophagus omalinus'},
        {'label': 'Staphylinidae - Aploderus caelatus'},
        {'label': 'Staphylinidae - Arpedium quadrum'},
        {'label': 'Staphylinidae - Atheta aeneipennis'},
        {'label': 'Staphylinidae - Atheta allocera'},
        {'label': 'Staphylinidae - Atheta altaica'},
        {'label': 'Staphylinidae - Atheta arctica'},
        {'label': 'Staphylinidae - Atheta atramentaria'},
        {'label': 'Staphylinidae - Atheta boleticola'},
        {'label': 'Staphylinidae - Atheta boreella'},
        {'label': 'Staphylinidae - Atheta brunneipennis'},
        {'label': 'Staphylinidae - Atheta celata'},
        {'label': 'Staphylinidae - Atheta cinnamoptera'},
        {'label': 'Staphylinidae - Atheta corvina'},
        {'label': 'Staphylinidae - Atheta cribrata'},
        {'label': 'Staphylinidae - Atheta debilis'},
        {'label': 'Staphylinidae - Atheta depressicollis'},
        {'label': 'Staphylinidae - Atheta diversa'},
        {'label': 'Staphylinidae - Atheta elongatula'},
        {'label': 'Staphylinidae - Atheta euryptera'},
        {'label': 'Staphylinidae - Atheta excellens'},
        {'label': 'Staphylinidae - Atheta excelsa'},
        {'label': 'Staphylinidae - Atheta graminicola'},
        {'label': 'Staphylinidae - Atheta hypnorum'},
        {'label': 'Staphylinidae - Atheta intermedia'},
        {'label': 'Staphylinidae - Atheta laevicauda'},
        {'label': 'Staphylinidae - Atheta laticollis'},
        {'label': 'Staphylinidae - Atheta melanocera'},
        {'label': 'Staphylinidae - Atheta myrmecobia'},
        {'label': 'Staphylinidae - Atheta palleola'},
        {'label': 'Staphylinidae - Atheta pilicornis'},
        {'label': 'Staphylinidae - Atheta procera'},
        {'label': 'Staphylinidae - Atheta setigera'},
        {'label': 'Staphylinidae - Atheta sodalis'},
        {'label': 'Staphylinidae - Atheta sparreschneideri'},
        {'label': 'Staphylinidae - Atheta spatuloides'},
        {'label': 'Staphylinidae - Atheta strandiella'},
        {'label': 'Staphylinidae - Atheta subtilis'},
        {'label': 'Staphylinidae - Atheta taxiceroides'},
        {'label': 'Staphylinidae - Atheta vaga'},
        {'label': 'Staphylinidae - Atrecus pilicornis'},
        {'label': 'Staphylinidae - Autalia puncticollis'},
        {'label': 'Staphylinidae - Bisnius nigriventris'},
        {'label': 'Staphylinidae - Bisnius puella'},
        {'label': 'Staphylinidae - Bolitochara pulchra'},
        {'label': 'Staphylinidae - Boreophilia islandica'},
        {'label': 'Staphylinidae - Bryophacis maklini'},
        {'label': 'Staphylinidae - Bryophacis rufus punctipennis'},
        {'label': 'Staphylinidae - Bryoporus cernuus'},
        {'label': 'Staphylinidae - Carpelimus bilineatus'},
        {'label': 'Staphylinidae - Coryphium angusticolle'},
        {'label': 'Staphylinidae - Dadobia immersa'},
        {'label': 'Staphylinidae - Deliphrum tectum'},
        {'label': 'Staphylinidae - Dinaraea aequata'},
        {'label': 'Staphylinidae - Dinaraea arcana'},
        {'label': 'Staphylinidae - Encephalus complicans'},
        {'label': 'Staphylinidae - Eucnecosum brachypterum'},
        {'label': 'Staphylinidae - Eudectus giraudi'},
        {'label': 'Staphylinidae - Euplectus karstenii'},
        {'label': 'Staphylinidae - Euplectus piceus'},
        {'label': 'Staphylinidae - Euplectus punctatus'},
        {'label': 'Staphylinidae - Euplectus signatus'},
        {'label': 'Staphylinidae - Eusphalerum lapponicum'},
        {'label': 'Staphylinidae - Eusphalerum minutum'},
        {'label': 'Staphylinidae - Gabrius appendiculatus'},
        {'label': 'Staphylinidae - Gabrius trossulus'},
        {'label': 'Staphylinidae - Gyrohypnus punctulatus'},
        {'label': 'Staphylinidae - Gyrophaena affinis'},
        {'label': 'Staphylinidae - Ischnoglossa prolixa'},
        {'label': 'Staphylinidae - Leptusa pulchella'},
        {'label': 'Staphylinidae - Liogluta alpestris'},
        {'label': 'Staphylinidae - Lomechusoides inflatus'},
        {'label': 'Staphylinidae - Lordithon lunulatus'},
        {'label': 'Staphylinidae - Lordithon speciosus'},
        {'label': 'Staphylinidae - Lordithon thoracicus'},
        {'label': 'Staphylinidae - Lordithon trimaculatus'},
        {'label': 'Staphylinidae - Lordithon trinotatus'},
        {'label': 'Staphylinidae - Lypoglossa lateralis'},
        {'label': 'Staphylinidae - Lyprocorrhe anceps'},
        {'label': 'Staphylinidae - Megarthrus nigrinus'},
        {'label': 'Staphylinidae - Megarthrus nitidulus'},
        {'label': 'Staphylinidae - Megarthrus prosseni'},
        {'label': 'Staphylinidae - Mniusa incrassata'},
        {'label': 'Staphylinidae - Mycetoporus erichsonanus'},
        {'label': 'Staphylinidae - Mycetoporus lepidus'},
        {'label': 'Staphylinidae - Mycetoporus maerkeli'},
        {'label': 'Staphylinidae - Mycetoporus mulsanti'},
        {'label': 'Staphylinidae - Mycetoporus punctus'},
        {'label': 'Staphylinidae - Notothecta flavipes'},
        {'label': 'Staphylinidae - Olisthaerus megacephalus'},
        {'label': 'Staphylinidae - Olophrum consimile'},
        {'label': 'Staphylinidae - Omalium rugatum'},
        {'label': 'Staphylinidae - Omalium septentrionis'},
        {'label': 'Staphylinidae - Omalium strigicolle'},
        {'label': 'Staphylinidae - Oxypoda brevicornis'},
        {'label': 'Staphylinidae - Oxypoda haemorrhoa'},
        {'label': 'Staphylinidae - Oxypoda lugubris'},
        {'label': 'Staphylinidae - Oxypoda nigricornis'},
        {'label': 'Staphylinidae - Oxypoda skalitzkyi'},
        {'label': 'Staphylinidae - Oxytelus laqueatus'},
        {'label': 'Staphylinidae - Paranopleta inhabilis'},
        {'label': 'Staphylinidae - Philonthus albipes'},
        {'label': 'Staphylinidae - Philonthus corvinus'},
        {'label': 'Staphylinidae - Philonthus politus'},
        {'label': 'Staphylinidae - Philonthus varians'},
        {'label': 'Staphylinidae - Phloeopora corticalis'},
        {'label': 'Staphylinidae - Placusa tachyporoides'},
        {'label': 'Staphylinidae - Proteinus brachypterus'},
        {'label': 'Staphylinidae - Quedius mesomelinus'},
        {'label': 'Staphylinidae - Quedius plagiatus'},
        {'label': 'Staphylinidae - Quedius xanthopus'},
        {'label': 'Staphylinidae - Scaphisoma agaricinum'},
        {'label': 'Staphylinidae - Stenichnus bicolor'},
        {'label': 'Staphylinidae - Stenus geniculatus'},
        {'label': 'Staphylinidae - Stenus hyperboreus'},
        {'label': 'Staphylinidae - Tachinus elongatus'},
        {'label': 'Staphylinidae - Tachinus laticollis'},
        {'label': 'Staphylinidae - Tachinus lignorum'},
        {'label': 'Staphylinidae - Tachinus pallipes'},
        {'label': 'Staphylinidae - Tachyporus chrysomelinus'},
        {'label': 'Staphylinidae - Tachyporus pulchellus'},
        {'label': 'Staphylinidae - Tetartopeus zetterstedti'},
        {'label': 'Staphylinidae - Thiasophila angulata'},
        {'label': 'Tetratomidae - Tetratoma ancora'},
        {'label': 'Zopheridae - Synchita humeralis'},
    ]
    for name in names:
        name['value'] = name['label'].split(' - ')[-1].split('(')[0]
    return names
