# -*- coding: utf-8 -*-

import ckan.logic as logic
from ckanext.scheming.helpers import scheming_get_dataset_schema
import json

_get_or_bust = logic.get_or_bust


def get_site_statistics():
    stats = {}
    stats['dataset_count'] = logic.get_action('package_search')(
        {}, {"rows": 1})['count']
    stats['group_count'] = len(logic.get_action('group_list')({}, {}))
    stats['organization_count'] = len(
        logic.get_action('organization_list')({}, {}))
    stats['user_count'] = len(
        logic.get_action('user_list')({}, {}))
    return stats

def data_dict_with_spatial(context, data_dict):
    #t = _get_or_bust(data_dict, "type")
    t = 'dataset'
    expanded = data_dict.get("expanded", True)
    s = scheming_get_dataset_schema(t, expanded)

    longitudes = []
    latitudes = []
    for field in s["dataset_fields"]:
        if field["field_name"] != "location":
            continue
        for choice in scheming_locations_choices(None):
            if choice["value"] not in data_dict.get("location", []):
                continue
            longitudes.append(choice["lon"])
            latitudes.append(choice["lat"])

    if not longitudes or not latitudes:
        return data_dict

    # create buffer (needed to index single-point bboxes)
    # longitude buffer: < 5.6 meters at latitude > 60 degrees
    # latitude buffer: ~11 meters
    e = 0.0001
    lon_min, lon_max = min(longitudes)-e, max(longitudes)+e
    lat_min, lat_max = min(latitudes)-e, max(latitudes)+e
    geometry = {
        "type": "Polygon",
        "coordinates": [
            [
                [lon_min, lat_max],
                [lon_max, lat_max],
                [lon_max, lat_min],
                [lon_min, lat_min],
                [lon_min, lat_max],
            ]
        ],
    }

    value = json.dumps(geometry)
    data_dict.setdefault("extras", [])  # ?
    for item in data_dict["extras"]:
        if item.get("key") == "spatial":
            item["value"] = value
            break
    else:
        data_dict["extras"].append({"key": "spatial", "value": value})

    return data_dict


def scheming_multiple_choice(field):
    if field.get("field_name") == "scientific_name":
        return scheming_scientific_name_choices(field)
    if field.get("field_name") == "location":
        return scheming_locations_choices(field)
    if field.get("field_name") == "tag_string":
        return scheming_tags_choices(field)
    return []


def scheming_tags_choices(field):
    return [
        {"value": "aerial-imagery", "label": "Aerial imagery"},
        {"value": "air-temperature", "label": "Air temperature"},
        {"value": "albedo", "label": "Albedo"},
        {"value": "artificial-nests", "label": "Artificial nests"},
        {"value": "barcoding", "label": "Barcoding"},
        {"value": "birch-forest", "label": "Birch forest"},
        {"value": "camera-traps", "label": "Camera traps"},
        {"value": "dendroecology", "label": "Dendroecology"},
        {"value": "distance-sampling", "label": "Distance sampling"},
        {"value": "dwarf-shrub-heath", "label": "Dwarf shrub heath"},
        {"value": "experimental-exclosures", "label": "Experimental exclosures"},
        {"value": "flight-intercept-traps", "label": "Flight intercept traps"},
        {"value": "forest", "label": "Forest"},
        {"value": "GPS-tags", "label": "GPS tags"},
        {"value": "grassy-tundra", "label": "Grassy tundra"},
        {"value": "ground-ice", "label": "Ground ice"},
        {"value": "ground-temperature", "label": "Ground temperature"},
        {"value": "heath", "label": "Heath"},
        {"value": "humidity", "label": "Humidity"},
        {"value": "hummock-tundra", "label": "Hummock tundra"},
        {"value": "hunting-records", "label": "Hunting records"},
        {"value": "ice-thickness", "label": "Ice thickness"},
        {"value": "icing", "label": "Icing"},
        {"value": "live-trapping", "label": "Live trapping"},
        {"value": "meadow", "label": "Meadow"},
        {"value": "metabarcoding", "label": "Metabarcoding"},
        {"value": "microsatellites", "label": "Microsatellites"},
        {"value": "modelling", "label": "Modelling"},
        {"value": "moss-tundra", "label": "Moss tundra"},
        {"value": "NDVI", "label": "NDVI"},
        {"value": "NIRS", "label": "NIRS"},
        {"value": "pellet-counts", "label": "Pellet counts"},
        {"value": "point-intercept", "label": "Point intercept"},
        {"value": "population-modelling", "label": "Population modelling"},
        {"value": "precipitation", "label": "Precipitation"},
        {"value": "radiation", "label": "Radiation"},
        {"value": "rain-on-snow", "label": "Rain on snow"},
        {"value": "remote-sensing", "label": "Remote sensing"},
        {"value": "repeat-photography", "label": "Repeat photography"},
        {"value": "satellite-imagery", "label": "Satellite imagery"},
        {"value": "satellite-tags", "label": "Satellite tags"},
        {"value": "scat-analysis", "label": "Scat analysis"},
        {"value": "snap-trapping", "label": "Snap trapping"},
        {"value": "snow-beds", "label": "Snow beds"},
        {"value": "snow-depth", "label": "Snow depth"},
        {"value": "snow-melt", "label": "Snow melt"},
        {"value": "snow-modelling", "label": "Snow modelling"},
        {"value": "snow-pits", "label": "Snow pits"},
        {"value": "snow-structure", "label": "Snow structure"},
        {"value": "snow-tracking", "label": "Snow tracking"},
        {"value": "soil-temperature", "label": "Soil temperature"},
        {"value": "stable-isotopes", "label": "Stable isotopes"},
        {"value": "surveys", "label": "Surveys"},
        {"value": "tall-shrub", "label": "Tall shrub"},
        {"value": "temperature", "label": "Temperature"},
        {"value": "temperature-logger", "label": "Temperature logger"},
        {"value": "timing-of-icing", "label": "Timing of icing"},
        {"value": "timing-of-snow-melt", "label": "Timing of snow melt"},
        {"value": "tundra", "label": "Tundra"},
        {"value": "weather-station", "label": "Weather station"},
        {"value": "wind", "label": "Wind"},
    ]


def scheming_locations_choices(field):
    locations = [
        {
            "label": "Svalbard",
            "lon": 16.1761980317877,
            "lat": 78.27838387,
        },
        {
            "label": "Svalbard - Kongsfjorden",
            "lon": 12.00434,
            "lat": 79.061159,
        },
        {
            "label": "Svalbard - Kongsfjorden - Blomstrandoya",
            "lon": 12.10577,
            "lat": 78.975803,
        },
        {
            "label": "Svalbard - Kongsfjorden - Broggerhalvoya",
            "lon": 11.735704,
            "lat": 78.914647,
        },
        {
            "label": "Svalbard - Kongsfjorden - Broggerhalvoya - Simlestupet",
            "lon": 11.735704,
            "lat": 78.914647,
        },
        {
            "label": "Svalbard - Kongsfjorden - Broggerhalvoya - Leinstranda",
            "lon": 11.735704,
            "lat": 78.914647,
        },
        {
            "label": "Svalbard - Kongsfjorden - Kaffioyra",
            "lon": 11.976978,
            "lat": 78.628325,
        },
        {
            "label": "Svalbard - Kongsfjorden - Ossiansarsfjellet",
            "lon": 12.476667,
            "lat": 78.942761,
        },
        {
            "label": "Svalbard - Kongsfjorden - Sarsoyra",
            "lon": 11.647155,
            "lat": 78.756613,
        },
        {
            "label": "Svalbard - Nordenkioldland",
            "lon": 15.116477,
            "lat": 78.013984,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Endalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Janssonhaugen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Bjorndalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Hanaskogdalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Malardalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Todalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Adventdalen - Bolterdalen",
            "lon": 16.250824,
            "lat": 78.179487,
        },
        {
            "label": "Svalbard - Nordenskioldland - Alkhornet",
            "lon": 13.741739,
            "lat": 78.215766,
        },
        {
            "label": "Svalbard - Nordenskioldland - Colesdalen",
            "lon": 15.202606,
            "lat": 78.080511,
        },
        {
            "label": "Svalbard - Nordenskioldland - Reindalen",
            "lon": 15.765129,
            "lat": 77.950241,
        },
        {
            "label": "Svalbard - Nordenskioldland - Sassendalen",
            "lon": 17.211454,
            "lat": 78.26552,
        },
        {
            "label": "Svalbard - Nordenskioldland - Sassendalen - Gjelhallet",
            "lon": 17.211454,
            "lat": 78.26552,
        },
        {
            "label": "Svalbard - Nordenskioldland - Sassendalen - Eskerdalen",
            "lon": 17.211454,
            "lat": 78.26552,
        },
        {
            "label": "Svalbard - Nordenskioldland - Semmeldalen",
            "lon": 15.416838,
            "lat": 77.966604,
        },
        {
            "label": "Varanger",
            "lon": 29.5298900097758,
            "lat": 70.39534162,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar",
            "lon": 27.514059,
            "lat": 70.60438,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Bekkarfjord",
            "lon": 27.476085,
            "lat": 70.705655,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Eastordalen",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Storelva",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Iesjohka",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Giksjohka",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Gurrojohka",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Siskkit corgas ja lagesduottar - Ifjordfjellet - Suoljavri",
            "lon": 27.4692352873563,
            "lat": 70.42233736,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu",
            "lon": 27.85705,
            "lat": 70.907408,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu - Nordkynn",
            "lon": 27.74431,
            "lat": 70.9333935,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu - Tana",
            "lon": 27.7096679608677,
            "lat": 70.07999344,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu - Skjaernes",
            "lon": 27.8498,
            "lat": 70.442,
        },
        {
            "label": "Varanger - Olggut corgas oarje deatnu - Boftsa",
            "lon": 28.178,
            "lat": 70.3701,
        },
        {
            "label": "Varanger - Bahcaveaijji",
            "lon": 29.185076,
            "lat": 69.78709,
        },
        {
            "label": "Varanger - Bahcaveaijji - Bugoyfjord",
            "lon": 29.3306369580431,
            "lat": 69.89285477,
        },
        {
            "label": "Varanger - Bahcaveaijji - Kirkenes",
            "lon": 29.350363333001,
            "lat": 69.76388,
        },
        {
            "label": "Varanger - Rakkonjarga",
            "lon": 28.8749670228275,
            "lat": 70.65542217,
        },
        {
            "label": "Varanger - Rakkonjarga - Austertana",
            "lon": 28.5673587353134,
            "lat": 70.43537992,
        },
        {
            "label": "Varanger - Rakkonjarga - Luftjok",
            "lon": 28.3815452755338,
            "lat": 70.25333517,
        },
        {
            "label": "Varanger - Rakkonjarga - Polmak",
            "lon": 27.9812148162841,
            "lat": 70.03199545,
        },
        {
            "label": "Varanger - Rakkonjarga - Polmak - Polmak finland",
            "lon": 27.9812148162841,
            "lat": 70.03199545,
        },
        {
            "label": "Varanger - Rakkonjarga - Polmak - Polmak norway",
            "lon": 27.9812148162841,
            "lat": 70.03199545,
        },
        {
            "label": "Varanger - Rakkonjarga - Stjernevann",
            "lon": 29.211285,
            "lat": 70.54163917,
        },
        {
            "label": "Varanger - Varjjatnjarga",
            "lon": 29.7042036634186,
            "lat": 70.36574553,
        },
        {
            "label": "Varanger - Varjjatnjarga - Bergebydalen",
            "lon": 29.016312,
            "lat": 70.236493,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Komagdalen ovre",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Komagdalen midtre",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Komagdalen nedre",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Sanfjorddalen",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Kjoltindan",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Gargas",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Ryggfjellet",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Hubejohka",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Komagdalen - Ruossachokka",
            "lon": 30.0043184621013,
            "lat": 70.33535233,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Torvhaugdalen",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Baeralveaijohka",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Jakobselv",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Reinhaugen",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Skoarrajohka",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Tranemyra",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
        {
            "label": "Varanger - Varjjatnjarga - Vestre Jakobselv - Gaasevannan",
            "lon": 29.0756827124289,
            "lat": 70.29141287,
        },
    ]
    for location in locations:
        label = location['label'].split(' - ')[-1]
        location['value'] = ''.join(c for c in label.lower() if c.isalpha())
    return sorted(locations, key = lambda kv: kv['label'])


def scheming_topic_category_choices(field):
    return [
        {"value": "Biota", "label": "Biota"},
        {"value": "Boundaries", "label": "Boundaries"},
        {"value": "Climatology", "label": "Climatology /Meteorology /Atmosphere"},
        {"value": "Economy", "label": "Economy"},
        {"value": "Elevation", "label": "Elevation"},
        {"value": "Environment", "label": "Environment"},
        {"value": "Farming", "label": "Farming"},
        {"value": "Geoscientific", "label": "Geoscientific Information"},
        {"value": "Health", "label": "Health"},
        {"value": "Imagery", "label": "Imagery / Base Maps / Earth Cover"},
        {"value": "Inland_Waters", "label": "Inland Waters"},
        {"value": "Intelligence", "label": "Intelligence / Military"},
        {"value": "Location", "label": "Location"},
        {"value": "Oceans", "label": "Oceans"},
        {"value": "Planning", "label": "Planning / Cadastre"},
        {"value": "Society", "label": "Society"},
        {"value": "Structure", "label": "Structure"},
        {"value": "Transportation", "label": "Transportation"},
        {"value": "utilities", "label": "Utilities / Communication"},
    ]


def scheming_scientific_name_choices(field):
    return [
        {"value": "alc/alc", "label": "Cervidae - Alces alces (elg)"},
        {"value": "can/lup", "label": "Canidae - Canis lupus (ulv)"},
        {"value": "cap/cap", "label": "Cervidae - Capreolus capreolus (rådyr)"},
        {"value": "cricetidae", "label": "Cricetidae"},
        {"value": "gul/gul", "label": "Mustelidae - Gulo gulo (jerv)"},
        {"value": "lem/lem", "label": "Cricetidae - Lemmus lemmus (lemen)"},
        {"value": "lep/tim", "label": "Leporidae - Lepus timidus (hare)"},
        {"value": "lut/lut", "label": "Mustelidae - Lutra lutra (oter)"},
        {"value": "lyn/lyn", "label": "Felidae - Lynx lynx (gaupe)"},
        {"value": "mic/agr", "label": "Cricetidae - Microtus agrestis (markmus)"},
        {"value": "mic/lev", "label": "Cricetidae - Microtus levis (østmarkmus)"},
        {"value": "mic/oec", "label": "Cricetidae - Microtus oeconomus (fjellmarkmus alt fjellrotte)"},
        {"value": "mus/erm", "label": "Mustelidae - Mustela erminea (røyskatt)"},
        {"value": "mus/niv", "label": "Mustelidae - Mustela nivalis (snømus)"},
        {"value": "myo/gla", "label": "Cricetidae - Myodes glareolus (klatremus)"},
        {"value": "myo/ruf", "label": "Cricetidae - Myodes rufocanus (gråsidemus)"},
        {"value": "myo/rut", "label": "Cricetidae - Myodes rutilus (rødmus)"},
        {"value": "neo/fod", "label": "Soricidae - Neomys fodiens (vannspissmus)"},
        {"value": "neo/vis", "label": "Mustelidae - Neovison vison (mink)"},
        {"value": "ovi/ari", "label": "Bovidae - Ovis aries (sau)"},
        {"value": "ran/tar", "label": "Cervidae - Rangifer tarandus (reinsdyr)"},
        {"value": "sor/ara", "label": "Soricidae - Sorex araneus (vanlig spissmus alt krattspissmus)"},
        {"value": "sor/cae", "label": "Soricidae - Sorex caecutiens (lappspsimus)"},
        {"value": "sor/miniti", "label": "Soricidae - Sorex minutissimus (knøttspismus)"},
        {"value": "sor/minitu", "label": "Soricidae - Sorex minutus (dvergspissmus)"},
        {"value": "sor/sp", "label": "Soricidae - Sorex sp"},
        {"value": "urs/arc", "label": "Ursidae - Ursus arctos (brunbjørn)"},
        {"value": "urs/mar", "label": "Ursidae - Ursus maritima (isbjørn)"},
        {"value": "vul/lag", "label": "Canidae - Vulpes lagopus (fjellrev)"},
        {"value": "vul/vul", "label": "Canidae - Vulpes vulpes (rødrev)"},
        {"value": "act/hyp", "label": "Actitis hypoleucos (strandsnipe)"},
        {"value": "ana/cre", "label": "Anas crecca (krikkand)"},
        {"value": "ans/bra", "label": "Anser brachyrhynchus (kortnebbgås)"},
        {"value": "ant/cer", "label": "Anthus cervinus (lappiplerke)"},
        {"value": "ant/pra", "label": "Anthus pratensis (heipiplerke)"},
        {"value": "ant/sp", "label": "Anthus sp (piplerke)"},
        {"value": "ant/tri", "label": "Anthus trivialis (trepiplerke)"},
        {"value": "aqu/chr", "label": "Aquila chrysaetos (kongeørn)"},
        {"value": "arc/red", "label": "Acanthis hornemanni (polarsisik)"},
        {"value": "are/int", "label": "Arenaria interpes (steinvender)"},
        {"value": "asi/fla", "label": "Asio flammeus (jordugle)"},
        {"value": "ayt/mar", "label": "Aythya marila (bergand)"},
        {"value": "bom/gar", "label": "Bombycilla garrulus (sidensvans)"},
        {"value": "bra/ber", "label": "Branta bernicla (ringgås)"},
        {"value": "bra/leu", "label": "Branta leucopsis (hvitkinngås)"},
        {"value": "bub/sca", "label": "Bubo scandiacus (snøugle)"},
        {"value": "buc/cla", "label": "Bucephala clangula (kvinand)"},
        {"value": "but/lag", "label": "Buteo lagopus (fjellvåk)"},
        {"value": "cal/alb", "label": "Calidris alba (sandløper)"},
        {"value": "cal/alp", "label": "Calidris alpina (myrsnipe)"},
        {"value": "cal/lap", "label": "Calcarius lapponicus (lappspurv)"},
        {"value": "cal/mar", "label": "Calidris maritima (fjæreplytt)"},
        {"value": "cal/min", "label": "Calidris minuta (dvergsnipe)"},
        {"value": "cal/tem", "label": "Calidris temminckii (temmincksnipe)"},
        {"value": "car/chl", "label": "Carduelis chloris (grønnfink)"},
        {"value": "car/fla", "label": "Carduelis flammea (gråsisik)"},
        {"value": "cha/hia", "label": "Charadrius hiaticula (sandlo)"},
        {"value": "cha/mor", "label": "Charadirus morinellus (boltit)"},
        {"value": "cin/cin", "label": "Cinclus cinclus (fossekall)"},
        {"value": "cla/hye", "label": "Clangula hyemalis (havelle)"},
        {"value": "cor/cora", "label": "Corvus corax (ravn)"},
        {"value": "cor/corn", "label": "Corvus cornix (kråke)"},
        {"value": "cuc/can", "label": "Cuculus canorus (gjøk)"},
        {"value": "emb/sch", "label": "Emberiza schoeniclus (sivspurv)"},
        {"value": "fal/col", "label": "Falco columbarius (dvergfalk)"},
        {"value": "fal/per", "label": "Falco peregrinus (vandrefalk)"},
        {"value": "fal/rus", "label": "Falco rusticolus (jaktfalk)"},
        {"value": "fal/tin", "label": "Falco tinnunculus (tårnfalk)"},
        {"value": "fic/hyp", "label": "Ficedula hypoleuca (svarthvit fluesnapper)"},
        {"value": "fri/mon", "label": "Fringilla montifringilla (bjørkefink)"},
        {"value": "gal/gal", "label": "Gallinago gallinago (enkeltbekkasin)"},
        {"value": "gav/arc", "label": "Gavia arctica (storlom)"},
        {"value": "gav/ste", "label": "Gavia stellata (smålom)"},
        {"value": "hal/alb", "label": "Haliaeetus albicilla (havørn)"},
        {"value": "hor/lar", "label": "Eremophila alpestris (fjellerke)"},
        {"value": "lag/lag", "label": "Lagopus lagopus (lirype)"},
        {"value": "lag/mut", "label": "Lagopus muta (fjellrype)"},
        {"value": "lag/mut/hyp", "label": "Lagopus muta hyperborea (svalbardrype)"},
        {"value": "lag/sp", "label": "Lagopus sp (rype)"},
        {"value": "lan/exc", "label": "Lanius excubitor (varsler)"},
        {"value": "lar/can", "label": "Larus canus (fiskemåke)"},
        {"value": "lim/lap", "label": "Limosa lapponica (lappspove)"},
        {"value": "lox/cur", "label": "Loxia curvirostra (grankorsnebb)"},
        {"value": "lus/sve", "label": "Luscinia svecica (blåstrupe)"},
        {"value": "mer/mer", "label": "Mergus merganser (laksand)"},
        {"value": "mer/ser", "label": "Mergus serrator (siland)"},
        {"value": "mot/alb", "label": "Motacilla alba (linerle)"},
        {"value": "mot/fla/thu", "label": "Motacilla flava thunbergi (såerle)"},
        {"value": "num/pha", "label": "Numenius phaeopus (småspove)"},
        {"value": "oen/oen", "label": "Oenanthe oenanthe (steinskvett)"},
        {"value": "pag/ebu", "label": "Pagophila eburnea (ismåke)"},
        {"value": "par/maj", "label": "Parus major (kjøttmeis)"},
        {"value": "per/inf", "label": "Perisoreus infaustus (lavskrike)"},
        {"value": "pha/ful", "label": "Phalaropus fulicarius (polarsvømmesnipe)"},
        {"value": "pha/lob", "label": "Phalaropus lobatus (svømmesnipe)"},
        {"value": "phi/pug", "label": "Philomachus pugnax (brushøne)"},
        {"value": "pho/pho", "label": "Phoenicurus phoenicurus (rødstjert)"},
        {"value": "phy/bor", "label": "Phylloscopus borealis (lappsanger)"},
        {"value": "phy/tro", "label": "Phylloscopus trochilus (løvsanger)"},
        {"value": "pic/pic", "label": "Pica pica (skjære)"},
        {"value": "plu/apr", "label": "Pluvialis apricaria (heilo)"},
        {"value": "poe/cin", "label": "Poecile cinctus (lappmeis)"},
        {"value": "poe/mon", "label": "Poecile montanus (granmeis)"},
        {"value": "sco/rus", "label": "Scolopax rusticola (rugde)"},
        {"value": "sno/bun", "label": "Plectrophenax nivalis (snøspurv)"},
        {"value": "ste/lon", "label": "Stercorarius longicaudus (fjelljo)"},
        {"value": "ste/parad", "label": "Sterna paradisaea (rødnebbterne)"},
        {"value": "ste/paras", "label": "Stercorarius parasiticus (tyvjo)"},
        {"value": "sur/ulu", "label": "Surnia ulula (haukugle)"},
        {"value": "tri/gla", "label": "Tringa glareola (grønnstilk)"},
        {"value": "tri/tot", "label": "Tringa totanus (rødstilk)"},
        {"value": "tur/ili", "label": "Turdus iliacus (rødvingetrost)"},
        {"value": "tur/phi", "label": "Turdus philomelos (måltrost)"},
        {"value": "tur/pil", "label": "Turdus pilaris (gråtrost)"},
        {"value": "agr/mer", "label": "Poaceae - Agrostis mertensii - Agrostis (fjellkvein)"},
        {"value": "agr/sp", "label": "Poaceae - Agrostis (kvein)"},
        {"value": "alc/alp", "label": "Rosaceae - Alchemilla alpina - Alchemilla (fjellmarikåpe)"},
        {"value": "alc/sp", "label": "Rosaceae - Alchemilla (marikåpe)"},
        {"value": "aln/inc", "label": "Betulaceae - Alnus incana - Alnus (gråor)"},
        {"value": "aln/sp", "label": "Betulaceae - Alnus (or)"},
        {"value": "and/pol", "label": "Ericaceae - Andromeda polifolia - Andromeda (kvitlyng)"},
        {"value": "ang/arc", "label": "Apiaceae - Angelica archangelica - Angelica (kvann)"},
        {"value": "ant/nip", "label": "Poaceae - Anthoxanthum nipponicum - Anthoxanthum (fjellgulaks)"},
        {"value": "ant/odo", "label": "Poaceae - Anthoxanthum odoratum - Anthoxanthum (gulaks)"},
        {"value": "ant/syl", "label": "Apiaceae - Anthriscus sylvestris - Anthriscus (hundekjeks)"},
        {"value": "arc/alp", "label": "Ericaceae - Arctous alpinus - Arctous (rypebær)"},
        {"value": "ath/dis", "label": "Athyriaceae - Athyrium distentifolium - Athyrium (fjellburkne)"},
        {"value": "ath/sp ", "label": "Athyriaceae - Athyrium (storburkne)"},
        {"value": "ath/sp ", "label": "Athyriaceae - Athyrium (storburkne)"},
        {"value": "ave/fle", "label": "Poaceae - Avenella flexuosa - Avenella (smyle)"},
        {"value": "bar/alp", "label": "Orobanchaceae - Bartsia alpina - Bartsia (svarttopp)"},
        {"value": "bet/nan", "label": "Betulaceae - Betula nana - Betula (dvergbjørk)"},
        {"value": "bet/pub", "label": "Betulaceae - Betula pubescens var pumila - Betula (fjellbjørk)"},
        {"value": "bis/viv", "label": "Polygonaceae - Bistorta vivipara - Bistorta (harerug)"},
        {"value": "bot/lun", "label": "Ophioglossaceae - Botrychium lunaria - Botrychium (marinøkkel)"},
        {"value": "cal/lap", "label": "Poaceae - Calamagrostis lapponica - Calamagrostis (finnmarksrørkvein)"},
        {"value": "cal/neg", "label": "Poaceae - Calamagrostis neglecta - Calamagrostis (smårørkvein)"},
        {"value": "cal/pal", "label": "Ranunculaceae - Caltha palustris - Caltha (bekkeblom)"},
        {"value": "cal/phr", "label": "Poaceae - Calamagrostis phragmitoides  - Calamagrostis (skogrørkvein)"},
        {"value": "cal/sp", "label": "Poaceae - Calamagrostis (rørkvein)"},
        {"value": "cam/rot", "label": "Campanulaceae - Campanula rotundifolia coll - Campanula (blåklokke)"},
        {"value": "car/aqu", "label": "Cyperaceae - Carex aquatilis agg - Carex (nordlandsstarr)"},
        {"value": "car/big", "label": "Cyperaceae - Carex bigelowii - Carex (stivstarr)"},
        {"value": "car/bru", "label": "Cyperaceae - Carex brunnescens - Carex (seterstarr)"},
        {"value": "car/can", "label": "Cyperaceae - Carex canescens - Carex (gråstarr)"},
        {"value": "car/lac", "label": "Cyperaceae - Carex lachenalii - Carex (rypestarr)"},
        {"value": "car/lim", "label": "Cyperaceae - Carex limosa - Carex (dystarr)"},
        {"value": "car/liv", "label": "Cyperaceae - Carex livida - Carex (blystarr)"},
        {"value": "car/nig", "label": "Cyperaceae - Carex nigra - Carex (slåttestarr)"},
        {"value": "car/pra", "label": "Brassicaceae - Cardamine pratensis agg - Cardamine (engkarse)"},
        {"value": "car/sax", "label": "Cyperaceae - Carex saxatilis  - Carex (blankstarr)"},
        {"value": "car/sp ", "label": "Cyperaceae - Carex sp  - Carex (starr)"},
        {"value": "car/vag", "label": "Cyperaceae - Carex vaginata - Carex (slirestarr)"},
        {"value": "caryophyllaceae", "label": "Caryophyllaceae"},
        {"value": "cer/alp", "label": "Caryophyllaceae - Cerastium alpinum agg - Cerastium (fjellarve)"},
        {"value": "cer/cer", "label": "Caryophyllaceae - Cerastium cerastoides - Cerastium (brearve)"},
        {"value": "cer/fon", "label": "Caryophyllaceae - Cerastium fontanum - Cerastium (arve)"},
        {"value": "cer/sp", "label": "Caryophyllaceae - Cerastium (arve)"},
        {"value": "cha/ang", "label": "Onagraceae - Chamerion angustifolium - Chamerion (geitrams)"},
        {"value": "cha/sue", "label": "Cornaceae - Chamaepericlymenum suecicum  - Chamaepericlymenum (skrubbær)"},
        {"value": "cir/het", "label": "Asteraceae  - Cirsium heterophyllum - Cirsium (kvitbladtistel)"},
        {"value": "com/pal", "label": "Rosaceae - Comarum palustre - Comarum (myrhatt)"},
        {"value": "des/alp", "label": "Poaceae - Deschampsia alpina - Deschampsia (fjellbunke)"},
        {"value": "des/ces", "label": "Poaceae - Deschampsia cespitosa - Deschampsia (sølvbunke)"},
        {"value": "dip/alp", "label": "Lycopodiaceae - Diphasiastrum alpinum - Diphasiastrum (fjelljamne)"},
        {"value": "emp/nig", "label": "Ericaceae - Empetrum nigrum  - Empetrum (krekling)"},
        {"value": "epi/ana", "label": "Onagraceae - Epilobium anagallidifolium - Epilobium (dvergmjølke)"},
        {"value": "epi/hor", "label": "Onagraceae - Epilobium hornemannii - Epilobium (setermjølke)"},
        {"value": "epi/pal", "label": "Onagraceae - Epilobium palustre - Epilobium (myrmjølke)"},
        {"value": "epi/sp", "label": "Onagraceae - Epilobium (mjølke)"},
        {"value": "equ/arv", "label": "Equisetaceae - Equisetum arvense - Equisetum (åkersnelle)"},
        {"value": "equ/pal", "label": "Equisetaceae - Equisetum palustre - Equisetum (myrsnelle)"},
        {"value": "equ/pra", "label": "Equisetaceae - Equisetum pratense - Equisetum (engsnelle)"},
        {"value": "equ/sp", "label": "Equisetaceae  - Equisetum (sneller)"},
        {"value": "equ/syl", "label": "Equisetaceae - Equisetum sylvaticum - Equisetum (skogsnelle)"},
        {"value": "equ/var", "label": "Equisetaceae - Equisetum variegatum - Equisetum (fjellsnelle)"},
        {"value": "eri/ang", "label": "Cyperaceae - Eriophorum angustifolium - Eriophorum (duskull)"},
        {"value": "eup/sp ", "label": "Orobanchaceae - Euphrasia (augnetrøst)"},
        {"value": "eup/wet", "label": "Orobanchaceae - Euphrasia wettsteinii - Euphrasia (fjellaugnetrøst)"},
        {"value": "fes/ovi", "label": "Poaceae - Festuca ovina - Festuca (sauesvingel)"},
        {"value": "fes/rub", "label": "Poaceae - Festuca rubra - Festuca (raudsvingel)"},
        {"value": "fes/rub/ric", "label": "Poaceae - Festuca rubra ssp richardsonii - Festuca (polarraudsvingel)"},
        {"value": "fes/sp", "label": "Poaceae - Festuca (svingel)"},
        {"value": "fil/ulm", "label": "Rosaceae - Filipendula ulmaria - Filipendula (mjødurt)"},
        {"value": "ger/syl", "label": "Geraniaceae - Geranium sylvaticum - Geranium (skogstorkenebb)"},
        {"value": "geu/riv", "label": "Rosaceae - Geum rivale - Geum (enghumleblom)"},
        {"value": "har/hyp", "label": "Ericaceae - Harrimanella hypnoides - Harrimanella (moselyng)"},
        {"value": "hie/odo", "label": "Poaceae - Hierochloe odorata - Hierochloe (vanleg marigras)"},
        {"value": "hie/sek", "label": "Asteraceae - Hieracium alpina agg - Hieracium (fjellsvæver)"},
        {"value": "hie/sp ", "label": "Asteraceae - Hieracium (svæve)"},
        {"value": "hup/sel", "label": "Lycopodiaceae  - Huperzia selago - Huperzia (lusegras)"},
        {"value": "hup/sel", "label": "Lycopodiaceae - Huperzia selago - Huperzia (polarlusegras)"},
        {"value": "jun/com", "label": "Cupressaceae - Juniperus communis - Juniperus (einer)"},
        {"value": "jun/fil", "label": "Juncaceae - Juncus filiformis - Juncus (trådsiv)"},
        {"value": "jun/sp", "label": "Juncaceae - Juncus (siv)"},
        {"value": "jun/tri", "label": "Juncaceae - Juncus trifidus - Juncus (rabbesiv)"},
        {"value": "kal/pro", "label": "Ericaceae - Kalmia procumbens - Kalmia (greplyng)"},
        {"value": "lin/bor", "label": "Linnaeaceae  - Linnaea borealis - Linnaea (linnea)"},
        {"value": "luz/mul", "label": "Juncaceae - Luzula multiflora - Luzula (engfrytle)"},
        {"value": "luz/pil", "label": "Juncaceae - Luzula pilosa - Luzula (hårfrytle)"},
        {"value": "luz/sp", "label": "Juncaceae - Luzula (frytle)"},
        {"value": "luz/sud", "label": "Juncaceae - Luzula sudetica - Luzula (myrfrytle)"},
        {"value": "lyc/ann", "label": "Lycopodiaceae - Lycopodium annotinum - Lycopodium (stri kråkefot)"},
        {"value": "lyc/cla", "label": "Lycopodiaceae - Lycopodium clavatum - Lycopodium (mjuk kråkefot)"},
        {"value": "lyc/sp", "label": "Lycopodiaceae  - Lycopodium (kråkefot)"},
        {"value": "mel/pra", "label": "Orobanchaceae - Melampyrum pratense - Melampyrum (stormarimjelle)"},
        {"value": "mel/sp", "label": "Orobanchaceae - Melampyrum (marimjelle)"},
        {"value": "mel/syl", "label": "Orobanchaceae - Melampyrum sylvaticum - Melampyrum (småmarimjelle)"},
        {"value": "mil/eff", "label": "Poaceae - Milium effusum - Milium (myskegras)"},
        {"value": "min/sp", "label": "Caryophyllaceae - Minuartia (tuvearve)"},
        {"value": "myo/sp", "label": "Boraginaceae - Myosotis (minneblom)"},
        {"value": "nar/str", "label": "Poaceae - Nardus stricta - Nardus (finnskjegg)"},
        {"value": "oma/nor", "label": "Asteraceae - Omalotheca norvegica - Omalotheca (setergråurt)"},
        {"value": "oma/sup", "label": "Asteraceae - Omalotheca supina - Omalotheca (dverggråurt)"},
        {"value": "ort/sec", "label": "Ericaceae - Orthilia secunda - Orthilia (nikkevintergrøn)"},
        {"value": "oxy/dig", "label": "Polygonaceae - Oxyria digyna - Oxyria (fjellsyre)"},
        {"value": "par/pal", "label": "Celastraceae - Parnassia palustris - Parnassia (jåblom)"},
        {"value": "ped/lap", "label": "Orobanchaceae - Pedicularis lapponica - Pedicularis (bleikmyrklegg)"},
        {"value": "ped/sp", "label": "Orobanchaceae - Pedicularis (myrklegg)"},
        {"value": "phl/alp", "label": "Poaceae - Phleum alpinum - Phleum (fjelltimotei)"},
        {"value": "phy/cae", "label": "Ericaceae - Phyllodoce caerulea - Phyllodoce (blålyng)"},
        {"value": "pin/vul", "label": "Lentibulariaceae - Pinguicula vulgaris - Pinguicula (vanleg tettegras)"},
        {"value": "poa/alp", "label": "Poaceae - Poa alpina - Poa (fjellrapp)"},
        {"value": "poa/arc", "label": "Poaceae - Poa arctica - Poa (jervrapp)"},
        {"value": "poa/pra/alp", "label": "Poaceae - Poa pratensis ssp alpigena - Poa (seterrapp)"},
        {"value": "poa/sp", "label": "Poaceae - Poa (rapp)"},
        {"value": "poaceae", "label": "Poaceae"},
        {"value": "pot/nor", "label": "Rosaceae - Potentilla norvegica - Potentilla (norsk mure)"},
        {"value": "pyr/min", "label": "Ericaceae - Pyrola minor - Pyrola (perlevintergrøn)"},
        {"value": "pyr/sp", "label": "Ericaceae - Pyrola (vintergrøn)"},
        {"value": "ran/acr", "label": "Ranunculaceae - Ranunculus acris agg - Ranunculus (engsoleie)"},
        {"value": "ran/rep", "label": "Ranunculaceae - Ranunculus repens - Ranunculus (krypsoleie)"},
        {"value": "ran/sp", "label": "Ranunculaceae - Ranunculus (soleie)"},
        {"value": "rhi/min", "label": "Orobanchaceae - Rhinanthus minor - Rhinanthus (småengkall)"},
        {"value": "rho/ros", "label": "Crassulaceae - Rhodiola rosea - Rhodiola (rosenrot)"},
        {"value": "rho/tom", "label": "Ericaceae - Rhododendron tomentosum - Rhododendron (finnmarkspors)"},
        {"value": "rub/cha", "label": "Rosaceae - Rubus chamaemorus - Rubus (molte)"},
        {"value": "rub/sax", "label": "Rosaceae - Rubus saxatalis - Rubus (teiebær)"},
        {"value": "rum/ace", "label": "Polygonaceae - Rumex acetosa - Rumex (engsyre)"},
        {"value": "sag/sag", "label": "Caryophyllaceae - Sagina saginoides - Sagina (seterarve)"},
        {"value": "sag/sp", "label": "Caryophyllaceae - Sagina (småarve)"},
        {"value": "sal/gla", "label": "Salicaceae - Salix glauca - Salix (sølvvier)"},
        {"value": "sal/has", "label": "Salicaceae - Salix hastata - Salix (bleikvier)"},
        {"value": "sal/her", "label": "Salicaceae  - Salix herbacea - Salix (musøre)"},
        {"value": "sal/lan", "label": "Salicaceae - Salix lanata agg - Salix (ullvier)"},
        {"value": "sal/lap", "label": "Salicaceae - Salix lapponum - Salix (lappvier)"},
        {"value": "sal/phy", "label": "Salicaceae - Salix phylicifolia agg - Salix (grønvier)"},
        {"value": "sal/sp", "label": "Salicaceae  - Salix (vier)"},
        {"value": "sau/alp", "label": "Asteraceae - Saussurea alpina - Saussurea (fjelltistel)"},
        {"value": "sco/aut", "label": "Asteraceae - Scorzoneroides autumnalis  - Leontodon (følblom)"},
        {"value": "sel/sel", "label": "Selaginellaceae - Selaginella selaginoides - Selaginella (dvergjamne)"},
        {"value": "sib/pro", "label": "Rosaceae - Sibbaldia procumbens - Sibbaldia (trefingerurt)"},
        {"value": "sol/vir", "label": "Asteraceae  - Solidago virgaurea - Solidago (gullris)"},
        {"value": "sor/auc", "label": "Rosaceae - Sorbus aucuparia - Sorbus (rogn)"},
        {"value": "ste/bor", "label": "Caryophyllaceae - Stellaria borealis - Stellaria (fjellstjerneblom)"},
        {"value": "ste/med", "label": "Caryophyllaceae - Stellaria media - Stellaria (vassarve)"},
        {"value": "ste/nem", "label": "Caryophyllaceae - Stellaria nemorum - Stellaria (skogstjerneblom)"},
        {"value": "ste/sp", "label": "Caryophyllaceae - Stellaria (stjerneblom)"},
        {"value": "tar/sp", "label": "Asteraceae - Taraxacum (løvetann)"},
        {"value": "tha/alp", "label": "Ranunculaceae - Thalictrum alpinum - Thalictrum (fjellfrøstjerne)"},
        {"value": "tri/ces", "label": "Cyperaceae - Trichophorum cespitosum - Trichophorum (bjønnskjegg)"},
        {"value": "tri/eur", "label": "Myrsinaceae  - Trientalis europaea - Trientalis (skogstjerne)"},
        {"value": "tri/spi", "label": "Poaceae - Trisetum spicatum - Trisetum (svartaks)"},
        {"value": "tro/eur", "label": "Ranunculaceae - Trollius europaeus - Trollius (ballblom)"},
        {"value": "vac/myr", "label": "Ericaceae - Vaccinium myrtillus - Vaccinium (blåbær)"},
        {"value": "vac/uli", "label": "Ericaceae - Vaccinium uliginosum - Vaccinium (blokkebær)"},
        {"value": "vac/vit", "label": "Ericaceae - Vaccinium vitis-idaea - Vaccinium (tyttebær)"},
        {"value": "vah/atr", "label": "Poaceae - Vahlodea atropurpurea - Vahlodea (rypebunke)"},
        {"value": "ver/alp", "label": "Plantaginaceae - Veronica alpina - Veronica (fjellveronika)"},
        {"value": "ver/sp", "label": "Plantaginaceae - Veronica (veronika)"},
        {"value": "vio/bif", "label": "Violaceae - Viola biflora - Viola (fjellfiol)"},
        {"value": "vio/epi", "label": "Violaceae - Viola epipsila - Viola (stor myrfiol)"},
        {"value": "vio/pal", "label": "Violaceae - Viola palustris agg - Viola (myrfiol)"},
        {"value": "vio/sp ", "label": "Violaceae - Viola (fiol)"},
        {"value": "arc/ful", "label": "Rhabdoweisiaceae - Arctoa - Arctoa fulvella (faksjøkelmose)"},
        {"value": "arc/sp", "label": "Rhabdoweisiaceae - Arctoa - Arctoa sp (jøkelmose)"},
        {"value": "bar/sp", "label": "Anastrophyllaceae - Barbilophozia - Barbilophozia sp (skjeggmose)"},
        {"value": "bra/sp", "label": "Brachytheciaceae - Brachythecium - Brachythecium sp (lundmose)"},
        {"value": "bry/sp", "label": "Bryaceae - Bryum - Bryum sp (vrangmose)"},
        {"value": "dic/fle", "label": "Dicranaceae - Dicranum - Dicranum flexicaule (lyngsigd)"},
        {"value": "dic/sco", "label": "Dicranaceae - Dicranum - Dicranum scoparium (ribbesigd)"},
        {"value": "dic/sp", "label": "Dicranaceae - Dicranum - Dicranum sp (sigdmose)"},
        {"value": "dis/sp", "label": "Ditrichaceae - Distichium - Distichium sp (planmose)"},
        {"value": "hyl/pyr", "label": "Hylocomiaceae - Hylocomiastrum - Hylocomiastrum pyrenaicum (seterhusmose)"},
        {"value": "hyl/sp", "label": "Hylocomiaceae - Hylocomiastrum - Hylocomiastrum sp (husmose)"},
        {"value": "hylocomium/sp", "label": "Hylocomiaceae - Hylocomium - Hylocomium sp (etasjemose)"},
        {"value": "hylocomium/splendens", "label": "Hylocomiaceae - Hylocomium - Hylocomium splendens (etasjemose)"},
        {"value": "kia/gla", "label": "Rhabdoweisiaceae - Kiaeria - Kiaeria glacialis (jøkelfrostmose)"},
        {"value": "kia/sp", "label": "Rhabdoweisiaceae - Kiaeria - Kiaeria sp (frostmose)"},
        {"value": "lop/sp", "label": "Lophoziaceae - Lophozia - Lophozia sp (flikmose)"},
        {"value": "lop/wen", "label": "Lophoziaceae - Lophozia - Lophozia wenzelii (skeiflik)"},
        {"value": "oli/her", "label": "Polytrichaceae - Oligotrichum - Oligotrichum hercynicum (grusmose)"},
        {"value": "oli/sp", "label": "Polytrichaceae - Oligotrichum - Oligotrichum sp (grusmose)"},
        {"value": "ple/sch", "label": "Hylocomiaceae - Pleurozium - Pleurozium schreberi (furumose)"},
        {"value": "ple/sp", "label": "Hylocomiaceae - Pleurozium - Pleurozium sp (furumose)"},
        {"value": "poh/sp", "label": "Mielichhoferiaceae - Pohlia - Pohlia sp (nikkemose)"},
        {"value": "poh/wah", "label": "Mielichhoferiaceae - Pohlia - Pohlia wahlenbergii (kaldnikke)"},
        {"value": "pol/sp", "label": "Polytrichaceae - Polytrichum - Polytrichum sp (bjørnemose)"},
        {"value": "psi/sp", "label": "Polytrichaceae - Psilopilum - Psilopilum sp (komagmose)"},
        {"value": "rac/sp", "label": "Grimmiaceae - Racomitrium - Racomitrium sp (gråmose)"},
        {"value": "san/unc", "label": "Amblystegiaceae  - Sanionia - Sanionia uncinata (bleikmose)"},
        {"value": "sci/sp", "label": "Brachytheciaceae - Sciuro-hypnum - Sciuro-hypnum sp (sprikelundmose)"},
        {"value": "sph/rus", "label": "Sphagnaceae - Sphagnum - Sphagnum russowii (tvaretorvmose)"},
        {"value": "sph/sp", "label": "Sphagnaceae - Sphagnum - Sphagnum sp (torvmose)"},
        {"value": "abd/aff", "label": "Melandryidae - Abdera affinis"},
        {"value": "aci/cre", "label": "Staphylinidae - Acidota crenata"},
        {"value": "acr/amb", "label": "Staphylinidae - Acrotona amblystegii"},
        {"value": "acr/bor", "label": "Staphylinidae - Acrostiba borealis"},
        {"value": "acr/cog", "label": "Ptiliidae - Acrotrichis cognata"},
        {"value": "acr/fas", "label": "Ptiliidae - Acrotrichis fascicularis"},
        {"value": "acr/fun", "label": "Staphylinidae - Acrotona fungi"},
        {"value": "acr/inf", "label": "Staphylinidae - Acrulia inflata"},
        {"value": "acr/int", "label": "Ptiliidae - Acrotrichis intermedia"},
        {"value": "acr/orb", "label": "Staphylinidae - Acrotona orbata"},
        {"value": "acr/par", "label": "Ptiliidae - Acrotrichis parva"},
        {"value": "acr/rug", "label": "Ptiliidae - Acrotrichis rugulosa"},
        {"value": "acr/ser", "label": "Ptiliidae - Acrotrichis sericans"},
        {"value": "acr/sil", "label": "Ptiliidae - Acrotrichis silvatica"},
        {"value": "acr/str", "label": "Ptiliidae - Acrotrichis strandi"},
        {"value": "aga/arc", "label": "Leiodidae - Agathidium arcticum"},
        {"value": "aga/con", "label": "Dytiscidae - Agabus congener"},
        {"value": "aga/con", "label": "Leiodidae - Agathidium confusum"},
        {"value": "aga/rot", "label": "Leiodidae - Agathidium rotundatum"},
        {"value": "ago/con", "label": "Carabidae - Agonum consimile"},
        {"value": "agr/aur", "label": "Geometridae - Agriopis aurantiaria (gul frostmåler)"},
        {"value": "ale/bru", "label": "Staphylinidae - Aleochara brundini"},
        {"value": "ale/moe", "label": "Staphylinidae - Aleochara moerens"},
        {"value": "ama/apr", "label": "Carabidae - Amara apricaria"},
        {"value": "ama/hyp", "label": "Carabidae - Amara hyperborea"},
        {"value": "ama/nig", "label": "Carabidae - Amara nigricornis"},
        {"value": "ami/ana", "label": "Staphylinidae - Amischa analis"},
        {"value": "amp/nig", "label": "Elateridae - Ampedus nigrinus (svart blodsmeller)"},
        {"value": "ana/arc", "label": "Scraptiidae - Anaspis arctica"},
        {"value": "ani/axi", "label": "Leiodidae - Anisotoma axillaris"},
        {"value": "ani/cas", "label": "Leiodidae - Anisotoma castanea"},
        {"value": "ani/gla", "label": "Leiodidae - Anisotoma glabra"},
        {"value": "ant/alp", "label": "Staphylinidae - Anthophagus alpinus"},
        {"value": "ant/oma", "label": "Staphylinidae - Anthophagus omalinus"},
        {"value": "aph/bor", "label": "Scarabaeidae - Aphodius borealis"},
        {"value": "aph/dep", "label": "Scarabaeidae - Aphodius depressus"},
        {"value": "aph/fas", "label": "Scarabaeidae - Aphodius fasciatus (smågjødselbille)"},
        {"value": "aph/lap", "label": "Scarabaeidae - Aphodius lapponum (fjellgjødselbille)"},
        {"value": "aph/pic", "label": "Scarabaeidae - Aphodius piceus (svartgjødselbille)"},
        {"value": "apl/cae", "label": "Staphylinidae - Aploderus caelatus"},
        {"value": "apl/tar", "label": "Melyridae - Aplocnemus tarsalis"},
        {"value": "arp/qua", "label": "Staphylinidae - Arpedium quadrum"},
        {"value": "asp/orb", "label": "Sphindidae - Aspidiphorus orbiculatus"},
        {"value": "ath/aen", "label": "Staphylinidae - Atheta aeneipennis"},
        {"value": "ath/all", "label": "Staphylinidae - Atheta allocera"},
        {"value": "ath/alt", "label": "Staphylinidae - Atheta altaica"},
        {"value": "ath/arc", "label": "Staphylinidae - Atheta arctica"},
        {"value": "ath/atr", "label": "Staphylinidae - Atheta atramentaria"},
        {"value": "ath/bol", "label": "Staphylinidae - Atheta boleticola"},
        {"value": "ath/bor", "label": "Staphylinidae - Atheta boreella"},
        {"value": "ath/bru", "label": "Staphylinidae - Atheta brunneipennis"},
        {"value": "ath/cel", "label": "Staphylinidae - Atheta celata"},
        {"value": "ath/cin", "label": "Staphylinidae - Atheta cinnamoptera"},
        {"value": "ath/cor", "label": "Staphylinidae - Atheta corvina"},
        {"value": "ath/cri", "label": "Staphylinidae - Atheta cribrata"},
        {"value": "ath/deb", "label": "Staphylinidae - Atheta debilis"},
        {"value": "ath/dep", "label": "Staphylinidae - Atheta depressicollis"},
        {"value": "ath/div", "label": "Staphylinidae - Atheta diversa"},
        {"value": "ath/elo", "label": "Staphylinidae - Atheta elongatula"},
        {"value": "ath/eur", "label": "Staphylinidae - Atheta euryptera"},
        {"value": "ath/exc", "label": "Staphylinidae - Atheta excellens"},
        {"value": "ath/exc", "label": "Staphylinidae - Atheta excelsa"},
        {"value": "ath/gra", "label": "Staphylinidae - Atheta graminicola"},
        {"value": "ath/hyp", "label": "Staphylinidae - Atheta hypnorum"},
        {"value": "ath/int", "label": "Staphylinidae - Atheta intermedia"},
        {"value": "ath/lae", "label": "Staphylinidae - Atheta laevicauda"},
        {"value": "ath/lat", "label": "Staphylinidae - Atheta laticollis"},
        {"value": "ath/mel", "label": "Staphylinidae - Atheta melanocera"},
        {"value": "ath/myr", "label": "Staphylinidae - Atheta myrmecobia"},
        {"value": "ath/pal", "label": "Staphylinidae - Atheta palleola"},
        {"value": "ath/pil", "label": "Staphylinidae - Atheta pilicornis"},
        {"value": "ath/pro", "label": "Staphylinidae - Atheta procera"},
        {"value": "ath/set", "label": "Staphylinidae - Atheta setigera"},
        {"value": "ath/sod", "label": "Staphylinidae - Atheta sodalis"},
        {"value": "ath/spa", "label": "Staphylinidae - Atheta sparreschneideri"},
        {"value": "ath/spa", "label": "Staphylinidae - Atheta spatuloides"},
        {"value": "ath/str", "label": "Staphylinidae - Atheta strandiella"},
        {"value": "ath/sub", "label": "Elateridae - Athous subfuscus"},
        {"value": "ath/sub", "label": "Staphylinidae - Atheta subtilis"},
        {"value": "ath/tax", "label": "Staphylinidae - Atheta taxiceroides"},
        {"value": "ath/vag", "label": "Staphylinidae - Atheta vaga"},
        {"value": "ato/aff", "label": "Cryptophagidae - Atomaria affinis"},
        {"value": "ato/api", "label": "Cryptophagidae - Atomaria apicalis"},
        {"value": "ato/his", "label": "Cryptophagidae - Atomaria hislopi"},
        {"value": "ato/lew", "label": "Cryptophagidae - Atomaria lewisi"},
        {"value": "ato/nit", "label": "Cryptophagidae - Atomaria nitidula"},
        {"value": "ato/pel", "label": "Cryptophagidae - Atomaria peltataeformis"},
        {"value": "atr/pil", "label": "Staphylinidae - Atrecus pilicornis"},
        {"value": "aut/pun", "label": "Staphylinidae - Autalia puncticollis"},
        {"value": "bem/gra", "label": "Carabidae - Bembidion grapii"},
        {"value": "bis/nig", "label": "Staphylinidae - Bisnius nigriventris"},
        {"value": "bis/pue", "label": "Staphylinidae - Bisnius puella"},
        {"value": "bol/pul", "label": "Staphylinidae - Bolitochara pulchra"},
        {"value": "bor/isl", "label": "Staphylinidae - Boreophilia islandica"},
        {"value": "bry/cer", "label": "Staphylinidae - Bryoporus cernuus"},
        {"value": "bry/mak", "label": "Staphylinidae - Bryophacis maklini"},
        {"value": "bry/ruf/pun", "label": "Staphylinidae - Bryophacis rufus punctipennis"},
        {"value": "byr/fas", "label": "Byrrhidae - Byrrhus fasciatus"},
        {"value": "cal/qua", "label": "Coccinellidae - Calvia quatuordecimguttata"},
        {"value": "car/bil", "label": "Staphylinidae - Carpelimus bilineatus"},
        {"value": "cat/alp", "label": "Leiodidae - Catops alpinus"},
        {"value": "cat/nig", "label": "Leiodidae - Catops nigrita"},
        {"value": "cat/tri", "label": "Leiodidae - Catops tristis"},
        {"value": "cer/fer", "label": "Cerylonidae - Cerylon ferrugineum"},
        {"value": "cer/lat", "label": "Hydrophilidae - Cercyon lateralis"},
        {"value": "cer/mel", "label": "Hydrophilidae - Cercyon melanocephalus"},
        {"value": "cer/qui", "label": "Hydrophilidae - Cercyon quisquilius"},
        {"value": "cis/bid", "label": "Ciidae - Cis bidentatus"},
        {"value": "cis/bol", "label": "Ciidae - Cis boleti"},
        {"value": "cis/com", "label": "Ciidae - Cis comptus"},
        {"value": "cis/com", "label": "Ciidaqe - Cis comptus"},
        {"value": "cis/sub", "label": "Ciidae - Cis submicans"},
        {"value": "cly/qua", "label": "Chrysomelidae - Clytra quadripunctata"},
        {"value": "coc/hie", "label": "Coccinellidae - Coccinella hieroglyphica"},
        {"value": "coc/tri", "label": "Coccinellidae - Coccinella trifasciata (fjellmarihøne)"},
        {"value": "coe/rub", "label": "Curculionidae - Coeliodinus rubicundus"},
        {"value": "col/ser", "label": "Leiodidae - Colon serripes"},
        {"value": "cor/ang", "label": "Staphylinidae - Coryphium angusticolle"},
        {"value": "cor/fer", "label": "Latridiidae - Corticaria ferruginea"},
        {"value": "cor/gib", "label": "Latridiidae - Cortinicara gibbosa"},
        {"value": "cor/min", "label": "Latridiidae - Corticarina minuta"},
        {"value": "cor/orb", "label": "Latridiidae - Corticaria orbicollis"},
        {"value": "cor/rub", "label": "Latridiidae - Corticaria rubripes"},
        {"value": "cry/cor", "label": "Cryptophagidae - Cryptophagus corticinus"},
        {"value": "cry/lap", "label": "Cryptophagidae - Cryptophagus lapponicus"},
        {"value": "cry/min", "label": "Hydrophilidae - Cryptopleurum minutum"},
        {"value": "cry/tub", "label": "Cryptophagidae - Cryptophagus tuberculosus"},
        {"value": "cyp/pad", "label": "Scirtidae - Cyphon padi"},
        {"value": "cyp/var", "label": "Scirtidae - Cyphon variabilis"},
        {"value": "cyt/ser", "label": "Byrrhidae - Cytilus sericeus"},
        {"value": "dad/imm", "label": "Staphylinidae - Dadobia immersa"},
        {"value": "das/obs", "label": "Melyridae - Dasytes obscurus"},
        {"value": "del/tec", "label": "Staphylinidae - Deliphrum tectum"},
        {"value": "den/bor", "label": "Elateridae - Denticollis borealis"},
        {"value": "den/lin", "label": "Elateridae - Denticollis linearis (øyesmeller)"},
        {"value": "dep/bet", "label": "Rhynchitidae - Deporaus betulae"},
        {"value": "dia/und", "label": "Elateridae - Diacanthous undulatus (huldresmeller)"},
        {"value": "dic/lap", "label": "Cantharidae - Dichelotarsus lapponicus"},
        {"value": "die/fil", "label": "Latridiidae - Dienerella filum"},
        {"value": "din/aeq", "label": "Staphylinidae - Dinaraea aequata"},
        {"value": "din/arc", "label": "Staphylinidae - Dinaraea arcana"},
        {"value": "dro/agi", "label": "Carabidae - Dromius agilis"},
        {"value": "ean/cos", "label": "Elateridae - Eanus costalis (tundrasmeller)"},
        {"value": "ela/der", "label": "Lymexylidae - Elateroides dermestoides"},
        {"value": "enc/com", "label": "Staphylinidae - Encephalus complicans"},
        {"value": "eni/fun", "label": "Latridiidae - Enicmus fungicola"},
        {"value": "eni/lun", "label": "Latridiidae - Enicmus lundbladi"},
        {"value": "epi/aut", "label": "Geometridae - Epirrita autumnata (fjellbjørkemåler)"},
        {"value": "epu/aes", "label": "Nitidulidae - Epuraea aestiva"},
        {"value": "epu/ang", "label": "Nitidulidae - Epuraea angustula"},
        {"value": "epu/bin", "label": "Nitidulidae - Epuraea binotata"},
        {"value": "epu/bor", "label": "Nitidulidae - Epuraea boreella"},
        {"value": "epu/mel", "label": "Nitidulidae - Epuraea melina"},
        {"value": "epu/ruf", "label": "Nitidulidae - Epuraea rufomarginata"},
        {"value": "epu/sil", "label": "Nitidulidae - Epuraea silacea"},
        {"value": "euc/bra", "label": "Staphylinidae - Eucnecosum brachypterum"},
        {"value": "eud/gir", "label": "Staphylinidae - Eudectus giraudi"},
        {"value": "eup/kar", "label": "Staphylinidae - Euplectus karstenii"},
        {"value": "eup/pic", "label": "Staphylinidae - Euplectus piceus"},
        {"value": "eup/pun", "label": "Staphylinidae - Euplectus punctatus"},
        {"value": "eup/sig", "label": "Staphylinidae - Euplectus signatus"},
        {"value": "eus/lap", "label": "Staphylinidae - Eusphalerum lapponicum"},
        {"value": "eus/min", "label": "Staphylinidae - Eusphalerum minutum"},
        {"value": "gab/app", "label": "Staphylinidae - Gabrius appendiculatus"},
        {"value": "gab/tro", "label": "Staphylinidae - Gabrius trossulus"},
        {"value": "gli/qua", "label": "Nitidulidae - Glischrochilus quadripunctatus"},
        {"value": "gon/dor", "label": "Anthribidae - Gonotropis dorsalis"},
        {"value": "gon/int", "label": "Chrysomelidae - Gonioctena intermedia"},
        {"value": "gyr/aff", "label": "Staphylinidae - Gyrophaena affinis"},
        {"value": "gyr/pun", "label": "Staphylinidae - Gyrohypnus punctulatus"},
        {"value": "hyd/sep", "label": "Leiodidae - Hydnobius septentrionalis"},
        {"value": "hyl/bru", "label": "Curculionidae - Hylastes brunneus (fururotbille)"},
        {"value": "isc/pro", "label": "Staphylinidae - Ischnoglossa prolixa"},
        {"value": "jud/sex", "label": "Cerambycidae - Judolia sexmaculata"},
        {"value": "lat/con", "label": "Latridiidae - Latridius consimilis"},
        {"value": "lat/hir", "label": "Latridiidae - Latridius hirtus"},
        {"value": "lat/min", "label": "Latridiidae - Latridius minutus"},
        {"value": "lat/por", "label": "Latridiidae - Latridius porcatus"},
        {"value": "lei/gyl", "label": "Leiodidae - Leiodes gyllenhalii"},
        {"value": "lei/ino", "label": "Leiodidae - Leiodes inordinata"},
        {"value": "lei/obe", "label": "Leiodidae - Leiodes obesa"},
        {"value": "lei/pun", "label": "Leiodidae - Leiodes punctulata"},
        {"value": "lei/sil", "label": "Leiodidae - Leiodes silesiaca"},
        {"value": "lep/pul", "label": "Staphylinidae - Leptusa pulchella"},
        {"value": "lio/aff", "label": "Elateridae - Liotrichus affinis (bjørkesmeller)"},
        {"value": "lio/alp", "label": "Staphylinidae - Liogluta alpestris"},
        {"value": "loc/cap", "label": "Chrysomelidae - Lochmaea caprea"},
        {"value": "lom/inf", "label": "Staphylinidae - Lomechusoides inflatus"},
        {"value": "lor/lun", "label": "Staphylinidae - Lordithon lunulatus"},
        {"value": "lor/pil", "label": "Carabidae - Loricera pilicornis"},
        {"value": "lor/spe", "label": "Staphylinidae - Lordithon speciosus"},
        {"value": "lor/tho", "label": "Staphylinidae - Lordithon thoracicus"},
        {"value": "lor/trim", "label": "Staphylinidae - Lordithon trimaculatus"},
        {"value": "lor/trin", "label": "Staphylinidae - Lordithon trinotatus"},
        {"value": "lyp/anc", "label": "Staphylinidae - Lyprocorrhe anceps"},
        {"value": "lyp/lat", "label": "Staphylinidae - Lypoglossa lateralis"},
        {"value": "mag/car", "label": "Curculionidae - Magdalis carbonaria"},
        {"value": "mal/bre", "label": "Cantharidae - Malthodes brevicollis"},
        {"value": "mal/fus", "label": "Cantharidae - Malthodes fuscus"},
        {"value": "mal/gut", "label": "Cantharidae - Malthodes guttifer"},
        {"value": "mal/mys", "label": "Cantharidae - Malthodes mysticus"},
        {"value": "meg/con", "label": "Hydrophilidae - Megasternum concinnum"},
        {"value": "meg/nig", "label": "Staphylinidae - Megarthrus nigrinus"},
        {"value": "meg/nit", "label": "Staphylinidae - Megarthrus nitidulus"},
        {"value": "meg/pro", "label": "Staphylinidae - Megarthrus prosseni"},
        {"value": "mis/arc", "label": "Carabidae - Miscodera arctica"},
        {"value": "mni/inc", "label": "Staphylinidae - Mniusa incrassata"},
        {"value": "myc/eri", "label": "Staphylinidae - Mycetoporus erichsonanus"},
        {"value": "myc/lep", "label": "Staphylinidae - Mycetoporus lepidus"},
        {"value": "myc/mae", "label": "Staphylinidae - Mycetoporus maerkeli"},
        {"value": "myc/mul", "label": "Mycetophagidae - Mycetophagus multipunctatus"},
        {"value": "myc/mul", "label": "Staphylinidae - Mycetoporus mulsanti"},
        {"value": "myc/pun", "label": "Staphylinidae - Mycetoporus punctus"},
        {"value": "nec/vio", "label": "Cleridae - Necrobia violacea"},
        {"value": "nec/vio", "label": "Melyridae - Necrobia violacea"},
        {"value": "neo/arc", "label": "Elateridae - Neohypdonus arcticus (grussmeller)"},
        {"value": "nep/bip", "label": "Coccinellidae - Nephus bipunctatus"},
        {"value": "nic/ves", "label": "Silphidae - Nicrophorus vespilloides"},
        {"value": "not/aqu", "label": "Carabidae - Notiophilus aquaticus"},
        {"value": "not/fla", "label": "Staphylinidae - Notothecta flavipes"},
        {"value": "oli/meg", "label": "Staphylinidae - Olisthaerus megacephalus"},
        {"value": "olo/con", "label": "Staphylinidae - Olophrum consimile"},
        {"value": "oma/rug", "label": "Staphylinidae - Omalium rugatum"},
        {"value": "oma/sep", "label": "Staphylinidae - Omalium septentrionis"},
        {"value": "oma/str", "label": "Staphylinidae - Omalium strigicolle"},
        {"value": "ope/bru", "label": "Geometridae - Operophtera brumata (liten frostmåler)"},
        {"value": "orc/mic", "label": "Melandryidae - Orchesia micans"},
        {"value": "orc/min", "label": "Melandryidae - Orchesia minor"},
        {"value": "ori/ser", "label": "Elateridae - Orithales serraticornis"},
        {"value": "ort/aln", "label": "Ciidae - Orthocis alni"},
        {"value": "oti/nod", "label": "Curculionidae - Otiorhynchus nodosus"},
        {"value": "oul/tub", "label": "Elmidae - Oulimnius tuberculatus"},
        {"value": "oxy/bre", "label": "Staphylinidae - Oxypoda brevicornis"},
        {"value": "oxy/hae", "label": "Staphylinidae - Oxypoda haemorrhoa"},
        {"value": "oxy/laq", "label": "Staphylinidae - Oxytelus laqueatus"},
        {"value": "oxy/lug", "label": "Staphylinidae - Oxypoda lugubris"},
        {"value": "oxy/nig", "label": "Staphylinidae - Oxypoda nigricornis"},
        {"value": "oxy/ska", "label": "Staphylinidae - Oxypoda skalitzkyi"},
        {"value": "par/imp", "label": "Elateridae - Paraphotistus impressus (hårsmeller)"},
        {"value": "par/inh", "label": "Staphylinidae - Paranopleta inhabilis"},
        {"value": "ped/fus", "label": "Silvanidae - Pediacus fuscus"},
        {"value": "pha/sub", "label": "Phalacridae - Phalacrus substriatus"},
        {"value": "phe/aen", "label": "Elateridae - Pheletes aeneoniger (skogsmeller)"},
        {"value": "phi/alb", "label": "Staphylinidae - Philonthus albipes"},
        {"value": "phi/cor", "label": "Staphylinidae - Philonthus corvinus"},
        {"value": "phi/pol", "label": "Staphylinidae - Philonthus politus"},
        {"value": "phi/var", "label": "Staphylinidae - Philonthus varians"},
        {"value": "phl/cor", "label": "Staphylinidae - Phloeopora corticalis"},
        {"value": "phr/vit", "label": "Chrysomelidae - Phratora vitellinae"},
        {"value": "pit/bid", "label": "Curculionidae - Pityogenes bidentatus (totannet barkbille)"},
        {"value": "pit/cha", "label": "Curculionidae - Pityogenes chalcographus"},
        {"value": "pla/tac", "label": "Staphylinidae - Placusa tachyporoides"},
        {"value": "pod/alp", "label": "Cantharidae - Podabrus alpinus"},
        {"value": "pod/sch", "label": "Cantharidae - Podistra schoenherri"},
        {"value": "pol/ful", "label": "Curculionidae - Polydrusus fulvicornis"},
        {"value": "pro/bra", "label": "Staphylinidae - Proteinus brachypterus"},
        {"value": "pro/met", "label": "Scarabaeidae - Protaetia metallica (maurgullbasse)"},
        {"value": "pte/for", "label": "Agyrtidae - Pteroloma forsstromii"},
        {"value": "que/mes", "label": "Staphylinidae - Quedius mesomelinus"},
        {"value": "que/pla", "label": "Staphylinidae - Quedius plagiatus"},
        {"value": "que/xan", "label": "Staphylinidae - Quedius xanthopus"},
        {"value": "rab/fov", "label": "Salpingidae - Rabocerus foveolatus"},
        {"value": "rha/elo", "label": "Cantharidae - Rhagonycha elongata"},
        {"value": "rha/mor", "label": "Cerambycidae - Rhagium mordax (løvtreløper)"},
        {"value": "rha/nig", "label": "Cantharidae - Rhagonycha nigriventris"},
        {"value": "rhi/cas", "label": "Curculionidae - Rhinoncus castor"},
        {"value": "rhi/dis", "label": "Monotomidae - Rhizophagus dispar"},
        {"value": "sal/ruf", "label": "Salpingidae - Salpingus ruficollis"},
        {"value": "sca/aga", "label": "Staphylinidae - Scaphisoma agaricinum"},
        {"value": "scy/fro", "label": "Coccinellidae - Scymnus frontalis"},
        {"value": "scy/nig", "label": "Coccinellidae - Scymnus nigrinus"},
        {"value": "sel/mel", "label": "Elateridae - Selatosomus melancholicus"},
        {"value": "ser/bru", "label": "Elateridae - Sericus brunneus (brunsmeller)"},
        {"value": "sim/sem", "label": "Byrrhidae - Simplocaria semistriata"},
        {"value": "sph/gla", "label": "Sphaeritidae - Sphaerites glabratus"},
        {"value": "ste/bic", "label": "Scydmaenidae - Stenichnus bicolor"},
        {"value": "ste/bic", "label": "Staphylinidae - Stenichnus bicolor"},
        {"value": "ste/gen", "label": "Staphylinidae - Stenus geniculatus"},
        {"value": "ste/hyp", "label": "Staphylinidae - Stenus hyperboreus"},
        {"value": "syn/hum", "label": "Zopheridae - Synchita humeralis"},
        {"value": "tac/chr", "label": "Staphylinidae - Tachyporus chrysomelinus"},
        {"value": "tac/elo", "label": "Staphylinidae - Tachinus elongatus"},
        {"value": "tac/lat", "label": "Staphylinidae - Tachinus laticollis"},
        {"value": "tac/lig", "label": "Staphylinidae - Tachinus lignorum"},
        {"value": "tac/pal", "label": "Staphylinidae - Tachinus pallipes"},
        {"value": "tac/pul", "label": "Staphylinidae - Tachyporus pulchellus"},
        {"value": "tet/anc", "label": "Tetratomidae - Tetratoma ancora"},
        {"value": "tet/zet", "label": "Staphylinidae - Tetartopeus zetterstedti"},
        {"value": "tha/lap", "label": "Silphidae - Thanatophilus lapponicus"},
        {"value": "thi/ang", "label": "Staphylinidae - Thiasophila angulata"},
        {"value": "tri/aen", "label": "Erotylidae - Triplax aenea"},
        {"value": "tri/rus", "label": "Erotylidae - Triplax russica"},
        {"value": "tri/scu", "label": "Erotylidae - Triplax scutellaris"},
        {"value": "try/sig", "label": "Curculionidae - Trypodendron signatum"},
    ]
